-- AUTO-GENERATED by tools/compile_guides.py from guides-src/DUNGEON_ALLIANCE_THE_TEMPLE_OF_ATAL_HAKKAR.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "DUNGEON_ALLIANCE_THE_TEMPLE_OF_ATAL_HAKKAR",
    name = "The Temple of Atal'Hakkar 48-55",
    version = 3,
    kind = "dungeon",
    faction = "Alliance",
    minLevel = 48,
    maxLevel = 55,
    map = 1435,
    zone = "Swamp of Sorrows",
    author = "ForeverGuide route planner",
    notes = "The Temple of Atal'Hakkar: the quests, the run and the turn-ins. Open it when you have a group.",
    stepCount = 20,
    steps = function() return {
        { type = "ACCEPT", quest = 1446, questName = "Jammal'an the Prophet", npc = 5598, npcName = "Atal'ai Exile", map = 1425, zone = "The Hinterlands", x = 33.6, y = 75.2 }, -- 1
        { type = "ACCEPT", quest = 4143, questName = "Haze of Evil", npc = 7775, npcName = "Gregan Brewspewer", map = 1444, zone = "Feralas", x = 45, y = 25.4 }, -- 2
        { type = "ACCEPT", quest = 3446, questName = "Into the Depths", npc = 7771, npcName = "Marvon Rivetseeker", map = 1446, zone = "Tanaris", x = 52.6, y = 45.8 }, -- 3
        { type = "ACCEPT", quest = 3447, questName = "Secret of the Circle", npc = 7771, npcName = "Marvon Rivetseeker", map = 1446, zone = "Tanaris", x = 52.6, y = 45.8 }, -- 4
        { type = "ACCEPT", quest = 3528, questName = "The God Hakkar", npc = 8579, npcName = "Yeh'kinya", map = 1446, zone = "Tanaris", x = 67, y = 22.4 }, -- 5
        { type = "ACCEPT", quest = 1475, questName = "Into The Temple of Atal'Hakkar", npc = 5384, npcName = "Brohann Caskbelly", map = 1453, zone = "Stormwind City", x = 64.2, y = 20.8 }, -- 6
        { type = "NOTE", map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5, text = "Find a group for The Temple of Atal'Hakkar", note = "All quests available from level 48; hand them in by level 55 for full XP" }, -- 7
        { type = "ACCEPT", quest = 3373, questName = "The Essence of Eranikus", map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 8
        { type = "COLLECT", quest = 1446, questName = "Jammal'an the Prophet", target = "Head of Jammal'an", count = 1, map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 9
        { type = "COLLECT", quest = 1475, questName = "Into The Temple of Atal'Hakkar", target = "Atal'ai Tablet", count = 10, map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 10
        { type = "COLLECT", quest = 3528, questName = "The God Hakkar", target = "Filled Egg of Hakkar", count = 1, map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 11
        { type = "COLLECT", quest = 3528, questName = "The God Hakkar", target = "Essence of Hakkar", count = 1, map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 12
        { type = "COLLECT", quest = 4143, questName = "Haze of Evil", target = "Atal'ai Haze", count = 5, map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 13
        { type = "TURNIN", quest = 3446, questName = "Into the Depths", map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 14
        { type = "TURNIN", quest = 3447, questName = "Secret of the Circle", map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 15
        { type = "TURNIN", quest = 3373, questName = "The Essence of Eranikus", map = 1435, zone = "Swamp of Sorrows", x = 69.9, y = 53.5 }, -- 16
        { type = "TURNIN", quest = 1446, questName = "Jammal'an the Prophet", npc = 5598, npcName = "Atal'ai Exile", map = 1425, zone = "The Hinterlands", x = 33.6, y = 75.2 }, -- 17
        { type = "TURNIN", quest = 1475, questName = "Into The Temple of Atal'Hakkar", npc = 5384, npcName = "Brohann Caskbelly", map = 1453, zone = "Stormwind City", x = 64.2, y = 20.8 }, -- 18
        { type = "TURNIN", quest = 3528, questName = "The God Hakkar", npc = 8579, npcName = "Yeh'kinya", map = 1446, zone = "Tanaris", x = 67, y = 22.4 }, -- 19
        { type = "TURNIN", quest = 4143, questName = "Haze of Evil", npc = 9119, npcName = "Muigin", map = 1449, zone = "Un'Goro Crater", x = 43, y = 9.6 }, -- 20
    } end,
})
