-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_SKYBORNE_52_SILITHUS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_SKYBORNE_52_SILITHUS",
    name = "52. Silithus 57-57 (Skyborne)",
    version = 2,
    faction = "Alliance",
    race = { "Skyborne" },
    minLevel = 57,
    maxLevel = 57,
    map = 1451,
    zone = "Silithus",
    next = "GEN_ALLIANCE_SKYBORNE_53_EASTERN_PLAGUELANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 52 of the Skyborne route: level 57 to 57, 21 steps, ~100 min of play in the model (47078 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 21,
    steps = function() return {
        { type = "TRAVEL", map = 1451, zone = "Silithus", x = 49.4, y = 37.1, radius = 60, note = "travel to Silithus (Silithus)" }, -- 1
        { type = "ACCEPT", quest = 8285, questName = "The Deserter", npc = 15183, npcName = "Geologist Larksbane", map = 1451, zone = "Silithus", x = 49.7, y = 37.5 }, -- 2
        { type = "ACCEPT", quest = 8318, questName = "Secret Communication", npc = 15306, npcName = "Bor Wildmane", map = 1451, zone = "Silithus", x = 48.6, y = 37.8 }, -- 3
        { type = "ACCEPT", quest = 9415, questName = "Report to Marshal Bluewall", npc = 17082, npcName = "Rifleman Torrig", map = 1451, zone = "Silithus", x = 50.7, y = 34.7 }, -- 4
        { type = "COLLECT", quest = 8318, questName = "Secret Communication", target = "Encrypted Twilight Text", count = 10, map = 1451, zone = "Silithus", x = 40.9, y = 42.2, near = true }, -- 5
        { type = "TURNIN", quest = 8318, questName = "Secret Communication", npc = 15306, npcName = "Bor Wildmane", map = 1451, zone = "Silithus", x = 48.6, y = 37.8 }, -- 6
        { type = "TURNIN", quest = 9415, questName = "Report to Marshal Bluewall", npc = 17080, npcName = "Marshal Bluewall", map = 1451, zone = "Silithus", x = 33.3, y = 51.1 }, -- 7
        { type = "ACCEPT", quest = 9419, questName = "Scouring the Desert", npc = 17080, npcName = "Marshal Bluewall", map = 1451, zone = "Silithus", x = 33.3, y = 51.1 }, -- 8
        { type = "KILL", quest = 9419, questName = "Scouring the Desert", npc = 17090, target = "Silithus Dust Turnin Quest Doodad", count = 1, map = 1451, zone = "Silithus", x = 33, y = 50.8 }, -- 9
        { type = "TURNIN", quest = 9419, questName = "Scouring the Desert", npc = 17080, npcName = "Marshal Bluewall", map = 1451, zone = "Silithus", x = 33.3, y = 51.1 }, -- 10
        { type = "TURNIN", quest = 8285, questName = "The Deserter", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 11
        { type = "ACCEPT", quest = 8279, questName = "The Twilight Lexicon", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 12
        { type = "KILL", quest = 8279, questName = "The Twilight Lexicon", npc = 11804, target = "Twilight Keeper Havunth", map = 1451, zone = "Silithus", x = 40.9, y = 42.2, note = "loot Twilight Lexicon - Chapter 3" }, -- 13
        { type = "KILL", quest = 8279, questName = "The Twilight Lexicon", npc = 15200, target = "Twilight Keeper Mayna", map = 1451, zone = "Silithus", x = 26.4, y = 36.6, note = "loot Twilight Lexicon - Chapter 1" }, -- 14
        { type = "KILL", quest = 8279, questName = "The Twilight Lexicon", npc = 11803, target = "Twilight Keeper Exeter", map = 1451, zone = "Silithus", x = 16.1, y = 86.4, note = "loot Twilight Lexicon - Chapter 2" }, -- 15
        { type = "TURNIN", quest = 8279, questName = "The Twilight Lexicon", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 16
        { type = "ACCEPT", quest = 8323, questName = "True Believers", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 17
        { type = "ACCEPT", quest = 8287, questName = "A Terrible Purpose", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 18
        { type = "COLLECT", quest = 8323, questName = "True Believers", target = "Encrypted Twilight Text", count = 10, map = 1451, zone = "Silithus", x = 41.5, y = 45.2, near = true }, -- 19
        { type = "TURNIN", quest = 8323, questName = "True Believers", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 20
        { type = "TURNIN", quest = 8287, questName = "A Terrible Purpose", npc = 15181, npcName = "Commander Mar'alith", map = 1451, zone = "Silithus", x = 49.2, y = 34.2 }, -- 21
    } end,
})
