-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_ORC_39_AZSHARA.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_ORC_39_AZSHARA",
    name = "39. Azshara 51-52 (Orc)",
    version = 2,
    faction = "Horde",
    race = { "Orc", "Troll" },
    minLevel = 51,
    maxLevel = 52,
    map = 1447,
    zone = "Azshara",
    next = "GEN_HORDE_ORC_40_FELWOOD",
    author = "ForeverGuide route planner",
    notes = "Chapter 39 of the Orc route: level 51 to 52, 1 steps, ~128 min of play in the model (36303 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 1,
    steps = function() return {
        { type = "GRIND", npc = 8761, target = "Mosshoof Courser", level = 52, map = 1447, zone = "Azshara", x = 66.4, y = 27.4, near = true, note = "grind Mosshoof Courser (level 52-53) to level 52 - nothing worth questing at 51" }, -- 1
    } end,
})
