-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_ORC_18_BADLANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_ORC_18_BADLANDS",
    name = "18. Badlands 39-40 (Orc)",
    version = 3,
    faction = "Horde",
    race = { "Orc", "Troll" },
    minLevel = 39,
    maxLevel = 40,
    map = 1418,
    zone = "Badlands",
    next = "GEN_HORDE_ORC_19_SWAMP_OF_SORROWS",
    author = "ForeverGuide route planner",
    notes = "Chapter 18 of the Orc route: level 39 to 40, 9 steps, ~81 min of play in the model (7218 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 11,
    steps = [[{
{type="TRAVEL",map=1434,zone="Stranglethorn Vale",x=26.9,y=77.1,radius=30,note="go to Gringer, the flight master (Booty Bay, Stranglethorn)"},
{type="FLY",map=1418,zone="Badlands",x=4,y=44.8,radius=30,note="fly to Kargath, Badlands"},
{type="TRAVEL",map=1418,zone="Kargath",x=2.8,y=45.9,radius=60,note="use your hearthstone (Kargath)"},
{type="TRAVEL",map=1418,zone="Badlands",x=3.5,y=46.8,radius=60,note="travel to Badlands (Badlands)"},
{type="ACCEPT",quest=2202,questName="Uldaman Reagent Run",npc=6868,npcName="Jarkal Mossmeld",map=1418,zone="Badlands",x=2.4,y=46.1},
{type="COLLECT",quest=2202,questName="Uldaman Reagent Run",target="Magenta Fungus Cap",count=12,map=1418,zone="Badlands",x=34,y=24.4,near=true},
{type="TURNIN",quest=2202,questName="Uldaman Reagent Run",npc=6868,npcName="Jarkal Mossmeld",map=1418,zone="Badlands",x=2.4,y=46.1},
{type="ACCEPT",quest=712,questName="Study of the Elements: Rock",npc=2921,npcName="Lotwil Veriatus",map=1418,zone="Badlands",x=26,y=44.9},
{type="KILL",quest=712,questName="Study of the Elements: Rock",npc=2736,target="Greater Rock Elemental",count=5,map=1418,zone="Badlands",x=6.6,y=76.3,near=true,note="loot Bracers of Rock Binding"},
{type="TURNIN",quest=712,questName="Study of the Elements: Rock",npc=2921,npcName="Lotwil Veriatus",map=1418,zone="Badlands",x=26,y=44.9},
{type="GRIND",npc=2729,target="Elder Crag Coyote",level=40,map=1418,zone="Badlands",x=24.3,y=58.6,near=true,note="grind Elder Crag Coyote (level 38-40) to level 40 - nothing worth questing at 39"}
}]],
})
