-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_HUMAN_31_SEARING_GORGE.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_HUMAN_31_SEARING_GORGE",
    name = "31. Searing Gorge 46-46 (Human)",
    version = 2,
    faction = "Alliance",
    race = { "Human" },
    minLevel = 46,
    maxLevel = 46,
    map = 1427,
    zone = "Searing Gorge",
    next = "GEN_ALLIANCE_HUMAN_32_THE_HINTERLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 31 of the Human route: level 46 to 46, 26 steps, ~120 min of play in the model (34200 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 26,
    steps = function() return {
        { type = "TRAVEL", map = 1427, zone = "Searing Gorge", x = 38.1, y = 32.5, radius = 60, note = "travel to Searing Gorge (Searing Gorge)" }, -- 1
        { type = "ACCEPT", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 2
        { type = "ACCEPT", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 3
        { type = "ACCEPT", quest = 7723, questName = "Curse These Fat Fingers", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 4
        { type = "ACCEPT", quest = 7724, questName = "Fiery Menace!", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 5
        { type = "ACCEPT", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 6
        { type = "KILL", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 5846, target = "Dark Iron Taskmaster", count = 15, map = 1427, zone = "Searing Gorge", x = 38, y = 32, near = true }, -- 7
        { type = "KILL", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 5844, target = "Dark Iron Slaver", count = 15, map = 1427, zone = "Searing Gorge", x = 38.4, y = 38, near = true }, -- 8
        { type = "TURNIN", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 14626, npcName = "Taskmaster Scrange", map = 1427, zone = "Searing Gorge", x = 39, y = 27.5 }, -- 9
        { type = "KILL", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 5840, target = "Dark Iron Steamsmith", map = 1427, zone = "Searing Gorge", x = 40, y = 48.3, near = true, note = "loot Smithing Tuyere" }, -- 10
        { type = "KILL", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 8566, target = "Dark Iron Lookout", map = 1427, zone = "Searing Gorge", x = 33.7, y = 51.9, near = true, note = "loot Lookout's Spyglass" }, -- 11
        { type = "KILL", quest = 7723, questName = "Curse These Fat Fingers", npc = 5854, target = "Heavy War Golem", count = 20, map = 1427, zone = "Searing Gorge", x = 32.5, y = 45.9, near = true }, -- 12
        { type = "KILL", quest = 7724, questName = "Fiery Menace!", npc = 5858, target = "Greater Lava Spider", count = 20, map = 1427, zone = "Searing Gorge", x = 29.5, y = 43.8, near = true }, -- 13
        { type = "KILL", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 9318, target = "Incendosaur", count = 20, map = 1427, zone = "Searing Gorge", x = 49.9, y = 39, near = true }, -- 14
        { type = "TURNIN", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 14626, npcName = "Taskmaster Scrange", map = 1427, zone = "Searing Gorge", x = 39, y = 27.5 }, -- 15
        { type = "TURNIN", quest = 7723, questName = "Curse These Fat Fingers", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 16
        { type = "TURNIN", quest = 7724, questName = "Fiery Menace!", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 17
        { type = "TURNIN", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 18
        { type = "ACCEPT", quest = 4449, questName = "Caught!", map = 1427, zone = "Searing Gorge", x = 65.6, y = 62.2 }, -- 19
        { type = "ACCEPT", quest = 3367, questName = "Suntara Stones", npc = 8284, npcName = "Dorius Stonetender", map = 1427, zone = "Searing Gorge", x = 63.9, y = 61 }, -- 20
        { type = "KILL", quest = 4449, questName = "Caught!", npc = 5839, target = "Dark Iron Geologist", count = 8, map = 1427, zone = "Searing Gorge", x = 63.9, y = 60.4, near = true }, -- 21
        { type = "COLLECT", quest = 4449, questName = "Caught!", target = "Silk Cloth", count = 8, map = 1427, zone = "Searing Gorge", x = 40.1, y = 41.5, near = true }, -- 22
        { type = "COMPLETE", quest = 3367, questName = "Suntara Stones", target = "Dorius Escort", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.4, note = "escort - stay close, it can fail: Dorius Escort" }, -- 23
        { type = "TURNIN", quest = 3367, questName = "Suntara Stones", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.3 }, -- 24
        { type = "ACCEPT", quest = 3368, questName = "Suntara Stones", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.3 }, -- 25
        { type = "TURNIN", quest = 4449, questName = "Caught!", map = 1427, zone = "Searing Gorge", x = 65.6, y = 62.2 }, -- 26
    } end,
})
