-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_SKYBORNE_01_ZEPHRAS_ISLE.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_SKYBORNE_01_ZEPHRAS_ISLE",
    name = "1. Zephras Isle 1-13 (Skyborne)",
    version = 3,
    faction = "Alliance",
    race = { "Skyborne" },
    minLevel = 1,
    maxLevel = 13,
    map = 2521,
    zone = "Zephras Isle",
    next = "GEN_ALLIANCE_SKYBORNE_02_DARKSHORE",
    author = "ForeverGuide route planner",
    notes = "Chapter 1 of the Skyborne route: level 1 to 13, 208 steps, ~182 min of play in the model (19955 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 225,
    steps = function() return {
        { type = "NOTE", map = 2521, zone = "Zephras Isle", x = 42.8, y = 24.1, text = "set your hearthstone at the inn in Zephras Isle (if there is one)" }, -- 1
        { type = "ACCEPT", quest = 92474, questName = "Falling With Style", map = 2521, zone = "Zephras Isle", x = 43.6, y = 24.0 }, -- 2
        { type = "ACCEPT", quest = 94414, questName = "The Anchors of Zephras", map = 2521, zone = "Zephras Isle", x = 43.5, y = 24.3 }, -- 3
        { type = "ACCEPT", quest = 92462, questName = "Infestation Investigation", map = 2521, zone = "Zephras Isle", x = 43.4, y = 24.8 }, -- 4
        { type = "KILL", quest = 92462, questName = "Infestation Investigation", target = "Pesky Cirrusfly", count = 8, map = 2521, zone = "Zephras Isle", x = 44.2, y = 26, near = true, note = "Pesky Cirrusfly slain" }, -- 5
        { type = "ACCEPT", quest = 92597, questName = "Reading the Ley Lines", map = 2521, zone = "Zephras Isle", x = 43.3, y = 24.9 }, -- 6
        { type = "ACCEPT", quest = 92473, questName = "Aggressive Encroachment", map = 2521, zone = "Zephras Isle", x = 42.4, y = 25.1 }, -- 7
        { type = "ACCEPT", quest = 92598, questName = "The Gift of Skysight", map = 2521, zone = "Zephras Isle", x = 42.6, y = 24.4 }, -- 8
        { type = "TURNIN", quest = 92462, questName = "Infestation Investigation", map = 2521, zone = "Zephras Isle", x = 43.4, y = 24.8 }, -- 9
        { type = "ACCEPT", quest = 92463, questName = "The Cirrusfly Queen", map = 2521, zone = "Zephras Isle", x = 43.4, y = 24.8 }, -- 10
        { type = "COMPLETE", quest = 94414, questName = "The Anchors of Zephras", target = "View the Anchor Pylon", map = 2521, zone = "Zephras Isle", x = 43.8, y = 24.1, note = "View the Anchor Pylon" }, -- 11
        { type = "TURNIN", quest = 94414, questName = "The Anchors of Zephras", map = 2521, zone = "Zephras Isle", x = 43.8, y = 24.1 }, -- 12
        { type = "COMPLETE", quest = 92474, questName = "Falling With Style", target = "Use Walk on Air", map = 2521, zone = "Zephras Isle", x = 42.1, y = 23.5, note = "Use Walk on Air" }, -- 13
        { type = "TURNIN", quest = 92474, questName = "Falling With Style", map = 2521, zone = "Zephras Isle", x = 42.1, y = 23.5 }, -- 14
        { type = "KILL", quest = 92473, questName = "Aggressive Encroachment", target = "Scrawny Ursera", count = 6, map = 2521, zone = "Zephras Isle", x = 41.0, y = 25.7, near = true, note = "loot Scrawny Ursera Claw" }, -- 15
        { type = "ACCEPT", quest = 92544, questName = "Al'Aketh Thugs", map = 2521, zone = "Zephras Isle", x = 38.3, y = 30.2 }, -- 16
        { type = "KILL", quest = 92463, questName = "The Cirrusfly Queen", target = "Cirrusfly Queen", count = 1, map = 2521, zone = "Zephras Isle", x = 48.4, y = 28.4, note = "Cirrusfly Queen slain" }, -- 17
        { type = "COMPLETE", quest = 92598, questName = "The Gift of Skysight", target = "Use your Skysight ability near the Elemental Convergence", map = 2521, zone = "Zephras Isle", x = 48.4, y = 20.4, note = "Use your Skysight ability near the Elemental Convergence" }, -- 18
        { type = "COMPLETE", quest = 92597, questName = "Reading the Ley Lines", target = "Use your Read Ley Line ability near the Thendal Grove Ley Line", map = 2521, zone = "Zephras Isle", x = 46.3, y = 17.9, note = "Use your Read Ley Line ability near the Thendal Grove Ley Line" }, -- 19
        { type = "KILL", quest = 92544, questName = "Al'Aketh Thugs", npc = 251145, target = "Al'Aketh Brute / Al'Aketh Brute / Malduko Cloudcrush", count = 6, map = 2521, zone = "Zephras Isle", x = 37.3, y = 32.9, near = true, note = "Al'Aketh Brute slain" }, -- 20
        { type = "TURNIN", quest = 92544, questName = "Al'Aketh Thugs", map = 2521, zone = "Zephras Isle", x = 38.3, y = 30.2 }, -- 21
        { type = "TURNIN", quest = 92463, questName = "The Cirrusfly Queen", map = 2521, zone = "Zephras Isle", x = 43.4, y = 24.8 }, -- 22
        { type = "TURNIN", quest = 92597, questName = "Reading the Ley Lines", map = 2521, zone = "Zephras Isle", x = 43.3, y = 24.9 }, -- 23
        { type = "TURNIN", quest = 92598, questName = "The Gift of Skysight", npc = 251487, npcName = "Ventaari Brightwish", map = 2521, zone = "Zephras Isle", x = 42.6, y = 24.4 }, -- 24
        { type = "TURNIN", quest = 92473, questName = "Aggressive Encroachment", map = 2521, zone = "Zephras Isle", x = 42.4, y = 25.1 }, -- 25
        { type = "ACCEPT", quest = 92553, questName = "Restocking the Larders", npc = 251905, npcName = "Zerril Softbreeze", map = 2521, zone = "Zephras Isle", x = 43.9, y = 43.8 }, -- 26
        { type = "ACCEPT", quest = 92595, questName = "The Windshapers", map = 2521, zone = "Zephras Isle", x = 43.5, y = 44.8 }, -- 27
        { type = "ACCEPT", quest = 92515, questName = "The Problem With Prideclaws", map = 2521, zone = "Zephras Isle", x = 44.7, y = 44.5 }, -- 28
        { type = "ACCEPT", quest = 92596, questName = "The High Order", map = 2521, zone = "Zephras Isle", x = 45.0, y = 46.5 }, -- 29
        { type = "ACCEPT", quest = 92514, questName = "Welcome to Shen'dar Village", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 30
        { type = "ACCEPT", quest = 93461, questName = "Welcome to Shen'dar Village", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 31
        { type = "COMPLETE", quest = 92596, questName = "The High Order", target = "Listen to Rathiril Sunlance", count = 1, map = 2521, zone = "Zephras Isle", x = 45.0, y = 46.5, note = "Listen to Rathiril Sunlance" }, -- 32
        { type = "TURNIN", quest = 92596, questName = "The High Order", map = 2521, zone = "Zephras Isle", x = 45.0, y = 46.4 }, -- 33
        { type = "ACCEPT", quest = 94413, questName = "A Magical Affront", map = 2521, zone = "Zephras Isle", x = 45.0, y = 46.4 }, -- 34
        { type = "KILL", quest = 92553, questName = "Restocking the Larders", npc = 251661, target = "Galestrider / Galestrider", count = 8, map = 2521, zone = "Zephras Isle", x = 43.1, y = 46.3, near = true, note = "loot Strider Meat" }, -- 35
        { type = "ACCEPT", quest = 92516, questName = "Hippogryph Harrassment", map = 2521, zone = "Zephras Isle", x = 44.5, y = 45.0 }, -- 36
        { type = "ACCEPT", quest = 93319, questName = "Pilfered Windstones", map = 2521, zone = "Zephras Isle", x = 44.5, y = 45.0 }, -- 37
        { type = "ACCEPT", quest = 93951, questName = "A Little Beauty", map = 2521, zone = "Zephras Isle", x = 44.9, y = 44.2 }, -- 38
        { type = "TURNIN", quest = 92553, questName = "Restocking the Larders", npc = 251905, npcName = "Zerril Softbreeze", map = 2521, zone = "Zephras Isle", x = 43.9, y = 43.8 }, -- 39
        { type = "COMPLETE", quest = 92514, questName = "Welcome to Shen'dar Village", target = "Speak with the Innkeeper", map = 2521, zone = "Zephras Isle", x = 43.0, y = 43.2, note = "Speak with the Innkeeper" }, -- 40
        { type = "TURNIN", quest = 92514, questName = "Welcome to Shen'dar Village", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 41
        { type = "ACCEPT", quest = 92517, questName = "The Criminal Element", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 42
        { type = "COMPLETE", quest = 93461, questName = "Welcome to Shen'dar Village", target = "Speak with the Innkeeper", map = 2521, zone = "Zephras Isle", x = 43.0, y = 43.2, note = "Speak with the Innkeeper" }, -- 43
        { type = "TURNIN", quest = 93461, questName = "Welcome to Shen'dar Village", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 44
        { type = "COMPLETE", quest = 92595, questName = "The Windshapers", target = "Listen to Illaya", count = 1, map = 2521, zone = "Zephras Isle", x = 43.5, y = 44.8, note = "Listen to Illaya" }, -- 45
        { type = "TURNIN", quest = 92595, questName = "The Windshapers", map = 2521, zone = "Zephras Isle", x = 43.5, y = 44.8 }, -- 46
        { type = "ACCEPT", quest = 94411, questName = "Meddlesome Mages", map = 2521, zone = "Zephras Isle", x = 43.5, y = 44.8 }, -- 47
        { type = "KILL", quest = 92515, questName = "The Problem With Prideclaws", npc = 251245, target = "Prideclaw", count = 10, map = 2521, zone = "Zephras Isle", x = 43.1, y = 46.3, near = true, note = "loot Prideclaw Pelt" }, -- 48
        { type = "ACCEPT", quest = 92551, questName = "Stolen Supplies", map = 2521, zone = "Zephras Isle", x = 45.2, y = 45.2 }, -- 49
        { type = "TURNIN", quest = 92515, questName = "The Problem With Prideclaws", npc = 251993, npcName = "Indari Sunseam", map = 2521, zone = "Zephras Isle", x = 44.7, y = 44.5 }, -- 50
        { type = "KILL", quest = 94411, questName = "Meddlesome Mages", npc = 257521, target = "High Order Apprentice", count = 6, map = 2521, zone = "Zephras Isle", x = 46.4, y = 38.6, note = "High Order Apprentice defeated" }, -- 51
        { type = "KILL", quest = 92517, questName = "The Criminal Element", npc = 251918, target = "Highlands Bandit / \"Badwind\" Bennic", count = 10, map = 2521, zone = "Zephras Isle", x = 46.4, y = 38.6, near = true, note = "Highlands Bandit slain" }, -- 52
        { type = "TURNIN", quest = 92517, questName = "The Criminal Element", npc = 251523, npcName = "Constable Aonda", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 53
        { type = "ACCEPT", quest = 93036, questName = "Infiltrating the Cult", npc = 251523, npcName = "Constable Aonda", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 54
        { type = "TURNIN", quest = 93036, questName = "Infiltrating the Cult", npc = 251904, npcName = "Sania Silverstream", map = 2521, zone = "Zephras Isle", x = 44.8, y = 45.5 }, -- 55
        { type = "TURNIN", quest = 94411, questName = "Meddlesome Mages", npc = 251902, npcName = "Illaya Amberwind", map = 2521, zone = "Zephras Isle", x = 43.5, y = 44.8 }, -- 56
        { type = "ACCEPT", quest = 92529, questName = "Falaath Village", npc = 251904, npcName = "Sania Silverstream", map = 2521, zone = "Zephras Isle", x = 44.8, y = 45.5 }, -- 57
        { type = "KILL", quest = 94413, questName = "A Magical Affront", target = "Windshaper Novice Seer", count = 6, map = 2521, zone = "Zephras Isle", x = 39.6, y = 47.2, near = true, note = "Windshaper Novice Seer defeated" }, -- 58
        { type = "KILL", quest = 92516, questName = "Hippogryph Harrassment", npc = 251261, target = "Hippogryph Matriarch / Hippogryph Matriarch / Hippogryph Matriarch", count = 8, map = 2521, zone = "Zephras Isle", x = 36.4, y = 50.9, near = true, note = "Hippogryph Youth slain" }, -- 59
        { type = "COLLECT", quest = 93951, questName = "A Little Beauty", target = "Hippogryph Down", count = 8, map = 2521, zone = "Zephras Isle", x = 36.4, y = 50.9, near = true, note = "Hippogryph Down" }, -- 60
        { type = "KILL", quest = 92551, questName = "Stolen Supplies", target = "Al'Aketh Stormcaller", count = 10, map = 2521, zone = "Zephras Isle", x = 41.0, y = 64.1, near = true, note = "Stolen Shen'dar Supplies" }, -- 61
        { type = "ACCEPT", quest = 94373, questName = "Call of Earth", npc = 257446, npcName = "Teo Hammerstorm", map = 1426, zone = "Dun Morogh", x = 28.8, y = 66.2, class = { "SHAMAN" }, note = "New in Forever" }, -- 62
        { type = "COLLECT", quest = 94373, questName = "Call of Earth", target = "Iceclaw Bear Pendant", count = 2, map = 1426, zone = "Dun Morogh", x = 30.4, y = 79.4, near = true, class = { "SHAMAN" } }, -- 63
        { type = "TURNIN", quest = 94373, questName = "Call of Earth", npc = 257446, npcName = "Teo Hammerstorm", map = 1426, zone = "Dun Morogh", x = 28.8, y = 66.2, class = { "SHAMAN" } }, -- 64
        { type = "KILL", quest = 93319, questName = "Pilfered Windstones", npc = 251918, target = "Highlands Bandit", count = 10, map = 2521, zone = "Zephras Isle", x = 46.4, y = 38.6, near = true, note = "Pilfered Windstone" }, -- 65
        { type = "TURNIN", quest = 93951, questName = "A Little Beauty", npc = 251991, npcName = "Taleen Shimmerthread", map = 2521, zone = "Zephras Isle", x = 44.9, y = 44.2 }, -- 66
        { type = "TURNIN", quest = 92516, questName = "Hippogryph Harrassment", npc = 251906, npcName = "Teeri Wellwind", map = 2521, zone = "Zephras Isle", x = 44.5, y = 45.0 }, -- 67
        { type = "TURNIN", quest = 93319, questName = "Pilfered Windstones", npc = 251906, npcName = "Teeri Wellwind", map = 2521, zone = "Zephras Isle", x = 44.5, y = 45.0 }, -- 68
        { type = "ACCEPT", quest = 93318, questName = "WANTED: Vulgara the Insatiable", map = 2521, zone = "Zephras Isle", x = 43.4, y = 45.9 }, -- 69
        { type = "TURNIN", quest = 94413, questName = "A Magical Affront", npc = 251903, npcName = "Rathiril Sunlance", map = 2521, zone = "Zephras Isle", x = 45.0, y = 46.4 }, -- 70
        { type = "KILL", quest = 93318, questName = "WANTED: Vulgara the Insatiable", target = "Vulgara", count = 1, map = 2521, zone = "Zephras Isle", x = 43.1, y = 51.0, near = true, note = "loot Vulgara's Head" }, -- 71
        { type = "TURNIN", quest = 93318, questName = "WANTED: Vulgara the Insatiable", npc = 252172, npcName = "Danarii Bellowveil", map = 2521, zone = "Zephras Isle", x = 45.2, y = 45.2 }, -- 72
        { type = "TURNIN", quest = 92529, questName = "Falaath Village", npc = 257065, npcName = "Missionary Jasaan", map = 2521, zone = "Zephras Isle", x = 46.9, y = 56.2 }, -- 73
        { type = "ACCEPT", quest = 92528, questName = "Among the Faithful", npc = 257065, npcName = "Missionary Jasaan", map = 2521, zone = "Zephras Isle", x = 46.9, y = 56.2 }, -- 74
        { type = "TURNIN", quest = 92551, questName = "Stolen Supplies", map = 2521, zone = "Zephras Isle", x = 49.8, y = 57.2 }, -- 75
        { type = "COMPLETE", quest = 92528, questName = "Among the Faithful", target = "Learn about the cultists' plans", count = 1, map = 2521, zone = "Zephras Isle", x = 48.8, y = 53.9, near = true, note = "Learn about the cultists' plans" }, -- 76
        { type = "TURNIN", quest = 92528, questName = "Among the Faithful", map = 2521, zone = "Zephras Isle", x = 46.4, y = 51.3 }, -- 77
        { type = "ACCEPT", quest = 92550, questName = "Havoc in the Highlands", map = 2521, zone = "Zephras Isle", x = 46.4, y = 51.3 }, -- 78
        { type = "ACCEPT", quest = 93926, questName = "The Western Watch", map = 2521, zone = "Zephras Isle", x = 46.4, y = 51.3 }, -- 79
        { type = "KILL", quest = 92550, questName = "Havoc in the Highlands", target = "Al'Aketh Stormcaller / Living Lightning", count = 6, map = 2521, zone = "Zephras Isle", x = 47.6, y = 54.1, near = true, note = "Al'Aketh Stormcaller slain" }, -- 80
        { type = "COMPLETE", quest = 92550, questName = "Havoc in the Highlands", target = "Commander Cyclas's Head", count = 1, map = 2521, zone = "Zephras Isle", x = 50.3, y = 57.0, note = "Commander Cyclas's Head" }, -- 81
        { type = "COMPLETE", quest = 93926, questName = "The Western Watch", target = "Check in on the Western Watchtower in the Shen'dar Highlands", count = 1, map = 2521, zone = "Zephras Isle", x = 42.3, y = 62.0, note = "Check in on the Western Watchtower in the Shen'dar Highlands" }, -- 82
        { type = "TURNIN", quest = 93926, questName = "The Western Watch", npc = 252155, npcName = "Piecekeeper Vaniel", map = 2521, zone = "Zephras Isle", x = 42.3, y = 62.0 }, -- 83
        { type = "ACCEPT", quest = 93927, questName = "A Last Request", npc = 252155, npcName = "Piecekeeper Vaniel", map = 2521, zone = "Zephras Isle", x = 42.3, y = 62.0 }, -- 84
        { type = "COLLECT", quest = 93927, questName = "A Last Request", target = "Collect and read the note", count = 1, map = 2521, zone = "Zephras Isle", x = 42.4, y = 62.1, note = "Collect and read the note" }, -- 85
        { type = "COMPLETE", quest = 93927, questName = "A Last Request", target = "Raani's Favorite Feather / Skypriest Aanders / Shadowsong Family Signet", count = 1, map = 2521, zone = "Zephras Isle", x = 41.1, y = 64.1, note = "Raani's Favorite Feather" }, -- 86
        { type = "TURNIN", quest = 92550, questName = "Havoc in the Highlands", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 87
        { type = "ACCEPT", quest = 92579, questName = "To Valanaar", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 88
        { type = "ACCEPT", quest = 92701, questName = "To Valanaar", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 89
        { type = "TURNIN", quest = 93927, questName = "A Last Request", map = 2521, zone = "Zephras Isle", x = 45.7, y = 45.5 }, -- 90
        { type = "ACCEPT", quest = 94374, questName = "Call of Earth", npc = 257446, npcName = "Teo Hammerstorm", map = 1426, zone = "Dun Morogh", x = 28.8, y = 66.2, class = { "SHAMAN" }, note = "New in Forever" }, -- 91
        { type = "TURNIN", quest = 94374, questName = "Call of Earth", npc = 5891, npcName = "Minor Manifestation of Earth", map = 1411, zone = "Durotar", x = 44, y = 76, class = { "SHAMAN" } }, -- 92
        { type = "ACCEPT", quest = 92698, questName = "What Is My Purpose?", npc = 250929, npcName = "Malfunctioning Cyclone Construct", map = 2521, zone = "Zephras Isle", x = 49.1, y = 78.4 }, -- 93
        { type = "TURNIN", quest = 92698, questName = "What Is My Purpose?", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 94
        { type = "ACCEPT", quest = 92682, questName = "Make Yourself Useful", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 95
        { type = "ACCEPT", quest = 92683, questName = "Flutterfly Dust", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 96
        { type = "ACCEPT", quest = 92684, questName = "Ornery Ornery Galestriders", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 97
        { type = "ACCEPT", quest = 92685, questName = "The Hills Have Eyes", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 98
        { type = "KILL", quest = 92683, questName = "Flutterfly Dust", npc = 251622, target = "Flutterfly", count = 5, map = 2521, zone = "Zephras Isle", x = 46.7, y = 77.0, near = true, note = "Flutterfly Dust" }, -- 99
        { type = "TURNIN", quest = 92683, questName = "Flutterfly Dust", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 100
        { type = "KILL", quest = 92682, questName = "Make Yourself Useful", npc = 252802, target = "Hungry Bandit / Hungry Bandit", count = 10, map = 2521, zone = "Zephras Isle", x = 46.2, y = 78.0, near = true, note = "Ripe Stormapple" }, -- 101
        { type = "TURNIN", quest = 92682, questName = "Make Yourself Useful", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 102
        { type = "KILL", quest = 92684, questName = "Ornery Ornery Galestriders", npc = 251707, target = "Ornery Galestrider", count = 7, map = 2521, zone = "Zephras Isle", x = 46.2, y = 78.0, near = true, note = "Lowlands Galestrider Tenderloin" }, -- 103
        { type = "TURNIN", quest = 92684, questName = "Ornery Ornery Galestriders", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 104
        { type = "KILL", quest = 92685, questName = "The Hills Have Eyes", npc = 252820, target = "Bandit Highwayman", count = 7, map = 2521, zone = "Zephras Isle", x = 45.8, y = 78.4, near = true, note = "loot Blood-Stained Bandit Mask" }, -- 105
        { type = "TURNIN", quest = 92685, questName = "The Hills Have Eyes", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 106
        { type = "ACCEPT", quest = 92693, questName = "Standing Our Ground", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.5 }, -- 107
        { type = "COMPLETE", quest = 92693, questName = "Standing Our Ground", target = "Follow Aamelia and make your final stand", count = 1, map = 2521, zone = "Zephras Isle", x = 47.5, y = 78.4, note = "Follow Aamelia and make your final stand" }, -- 108
        { type = "COMPLETE", quest = 92693, questName = "Standing Our Ground", target = "Speak with Aamelia Windfield", count = 1, map = 2521, zone = "Zephras Isle", x = 46.7, y = 81.9, note = "Speak with Aamelia Windfield" }, -- 109
        { type = "TURNIN", quest = 92693, questName = "Standing Our Ground", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 46.7, y = 81.9 }, -- 110
        { type = "ACCEPT", quest = 94375, questName = "Call of Earth", npc = 5891, npcName = "Minor Manifestation of Earth", map = 1411, zone = "Durotar", x = 44, y = 76, class = { "SHAMAN" }, note = "New in Forever" }, -- 111
        { type = "TURNIN", quest = 94375, questName = "Call of Earth", npc = 257446, npcName = "Teo Hammerstorm", map = 1426, zone = "Dun Morogh", x = 28.8, y = 66.2, class = { "SHAMAN" } }, -- 112
        { type = "TURNIN", quest = 92579, questName = "To Valanaar", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 113
        { type = "ACCEPT", quest = 92699, questName = "The Supreme Magister", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 114
        { type = "ACCEPT", quest = 92700, questName = "The Grand Skyseer", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 115
        { type = "ACCEPT", quest = 92679, questName = "Blood Tithe", npc = 252448, npcName = "Alvarion Windfield", map = 2521, zone = "Zephras Isle", x = 62.1, y = 73.3 }, -- 116
        { type = "ACCEPT", quest = 94897, questName = "The Fate of a Loved One", npc = 259012, npcName = "Ealaane Nimbuswalker", map = 2521, zone = "Zephras Isle", x = 66.0, y = 74.3 }, -- 117
        { type = "ACCEPT", quest = 92840, questName = "Catching Wind", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 118
        { type = "TURNIN", quest = 92699, questName = "The Supreme Magister", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 119
        { type = "TURNIN", quest = 92701, questName = "To Valanaar", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 120
        { type = "ACCEPT", quest = 92727, questName = "The Missing Scholar", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 121
        { type = "ACCEPT", quest = 92709, questName = "A Grand Adventure", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 122
        { type = "COMPLETE", quest = 92709, questName = "A Grand Adventure", target = "Listen to Elaadrin", count = 1, map = 2521, zone = "Zephras Isle", x = 64.2, y = 79.4, note = "Listen to Elaadrin" }, -- 123
        { type = "ACCEPT", quest = 93791, questName = "Speak with Belann", map = 2521, zone = "Zephras Isle", x = 62.9, y = 77.5 }, -- 124
        { type = "TURNIN", quest = 93791, questName = "Speak with Belann", map = 2521, zone = "Zephras Isle", x = 62.9, y = 77.5 }, -- 125
        { type = "TURNIN", quest = 92700, questName = "The Grand Skyseer", npc = 251968, npcName = "Ayessa Dawnsinger", map = 2521, zone = "Zephras Isle", x = 61.5, y = 76.9 }, -- 126
        { type = "TURNIN", quest = 92709, questName = "A Grand Adventure", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 127
        { type = "ACCEPT", quest = 93735, questName = "The Broken Construct", npc = 251968, npcName = "Ayessa Dawnsinger", map = 2521, zone = "Zephras Isle", x = 61.5, y = 76.9 }, -- 128
        { type = "ACCEPT", quest = 92708, questName = "A Grand Adventure", npc = 251968, npcName = "Ayessa Dawnsinger", map = 2521, zone = "Zephras Isle", x = 61.5, y = 76.9 }, -- 129
        { type = "TURNIN", quest = 93735, questName = "The Broken Construct", npc = 256083, npcName = "Riaani Nightwind", map = 2521, zone = "Zephras Isle", x = 59.1, y = 73.0 }, -- 130
        { type = "COMPLETE", quest = 92708, questName = "A Grand Adventure", target = "Listen to Ayessa", count = 1, map = 2521, zone = "Zephras Isle", x = 59.3, y = 80.0, note = "Listen to Ayessa" }, -- 131
        { type = "TURNIN", quest = 92708, questName = "A Grand Adventure", npc = 251968, npcName = "Ayessa Dawnsinger", map = 2521, zone = "Zephras Isle", x = 59.1, y = 79.8 }, -- 132
        { type = "COMPLETE", quest = 92679, questName = "Blood Tithe", target = "Find Aamelia Windfield", count = 1, map = 2521, zone = "Zephras Isle", x = 46.7, y = 82.0, note = "Find Aamelia Windfield" }, -- 133
        { type = "TURNIN", quest = 92679, questName = "Blood Tithe", npc = 252800, npcName = "Aamelia Windfield", map = 2521, zone = "Zephras Isle", x = 46.7, y = 81.9 }, -- 134
        { type = "COMPLETE", quest = 92840, questName = "Catching Wind", target = "Protect the Index", count = 1, map = 2521, zone = "Zephras Isle", x = 47.9, y = 69.0, note = "Protect the Index" }, -- 135
        { type = "TURNIN", quest = 92727, questName = "The Missing Scholar", map = 2521, zone = "Zephras Isle", x = 53.3, y = 72.2 }, -- 136
        { type = "ACCEPT", quest = 92849, questName = "The Missing Scholar", map = 2521, zone = "Zephras Isle", x = 53.3, y = 72.2 }, -- 137
        { type = "COMPLETE", quest = 92849, questName = "The Missing Scholar", target = "Carry Fillion Flamebreeze to safety while avoiding enemies", count = 1, map = 2521, zone = "Zephras Isle", x = 52.0, y = 69.4, note = "Carry Fillion Flamebreeze to safety while avoiding enemies" }, -- 138
        { type = "COMPLETE", quest = 92849, questName = "The Missing Scholar", target = "Find Fillion Flamebreeze", count = 1, map = 2521, zone = "Zephras Isle", x = 50.7, y = 65.4, note = "Find Fillion Flamebreeze" }, -- 139
        { type = "TURNIN", quest = 92849, questName = "The Missing Scholar", map = 2521, zone = "Zephras Isle", x = 52.1, y = 69.4 }, -- 140
        { type = "ACCEPT", quest = 92850, questName = "The Missing Scholar", map = 2521, zone = "Zephras Isle", x = 52.1, y = 69.4 }, -- 141
        { type = "COMPLETE", quest = 92850, questName = "The Missing Scholar", target = "Shriekling Matriarch's Head", count = 1, map = 2521, zone = "Zephras Isle", x = 52.0, y = 65.5, note = "Shriekling Matriarch's Head" }, -- 142
        { type = "ACCEPT", quest = 98512, questName = "Al'Aketh Assassins", map = 2521, zone = "Zephras Isle", x = 56.8, y = 61.1 }, -- 143
        { type = "COMPLETE", quest = 94897, questName = "The Fate of a Loved One", target = "Resaan's Heirloom", count = 1, map = 2521, zone = "Zephras Isle", x = 57.0, y = 29.4, note = "Resaan's Heirloom" }, -- 144
        { type = "KILL", quest = 98512, questName = "Al'Aketh Assassins", target = "Al'Aketh Assassin", count = 10, map = 2521, zone = "Zephras Isle", x = 55.7, y = 59.9, note = "Al'Aketh Assassin slain" }, -- 145
        { type = "TURNIN", quest = 98512, questName = "Al'Aketh Assassins", map = 2521, zone = "Zephras Isle", x = 56.8, y = 61.1 }, -- 146
        { type = "TURNIN", quest = 92850, questName = "The Missing Scholar", map = 2521, zone = "Zephras Isle", x = 66.3, y = 79.9 }, -- 147
        { type = "TURNIN", quest = 92840, questName = "Catching Wind", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 148
        { type = "TURNIN", quest = 94897, questName = "The Fate of a Loved One", map = 2521, zone = "Zephras Isle", x = 66.0, y = 74.3 }, -- 149
        { type = "ACCEPT", quest = 92860, questName = "In Service of Zephras", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 150
        { type = "TURNIN", quest = 92860, questName = "In Service of Zephras", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 151
        { type = "ACCEPT", quest = 93320, questName = "Tower Defense", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 152
        { type = "TURNIN", quest = 93320, questName = "Tower Defense", map = 2521, zone = "Zephras Isle", x = 69.6, y = 67.1 }, -- 153
        { type = "ACCEPT", quest = 92642, questName = "Disrupting Logistics", map = 2521, zone = "Zephras Isle", x = 69.6, y = 67.1 }, -- 154
        { type = "ACCEPT", quest = 92645, questName = "Breaking the Breaker", map = 2521, zone = "Zephras Isle", x = 69.6, y = 67.1 }, -- 155
        { type = "KILL", quest = 92642, questName = "Disrupting Logistics", target = "Al'Aketh Healer / Al'Aketh Brawler", count = 4, map = 2521, zone = "Zephras Isle", x = 66.1, y = 67.7, note = "Al'Aketh Healer slain" }, -- 156
        { type = "TURNIN", quest = 92642, questName = "Disrupting Logistics", map = 2521, zone = "Zephras Isle", x = 69.6, y = 67.1 }, -- 157
        { type = "ACCEPT", quest = 92880, questName = "Return to Valanaar", map = 2521, zone = "Zephras Isle", x = 69.6, y = 67.1 }, -- 158
        { type = "KILL", quest = 92645, questName = "Breaking the Breaker", target = "Commander Belguilos", count = 1, map = 2521, zone = "Zephras Isle", x = 65.7, y = 65.6, note = "Commander Belguilos slain" }, -- 159
        { type = "TURNIN", quest = 92645, questName = "Breaking the Breaker", map = 2521, zone = "Zephras Isle", x = 69.6, y = 67.1 }, -- 160
        { type = "TURNIN", quest = 92880, questName = "Return to Valanaar", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 161
        { type = "ACCEPT", quest = 92881, questName = "The High Elder's Request", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 162
        { type = "TURNIN", quest = 92881, questName = "The High Elder's Request", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 163
        { type = "ACCEPT", quest = 92643, questName = "The Turncoat", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 164
        { type = "COMPLETE", quest = 92643, questName = "The Turncoat", target = "Find the Al'Aketh Turncoat / Find the secluded house in Shen'dar Highlands", count = 1, map = 2521, zone = "Zephras Isle", x = 56.5, y = 60.9, note = "Find the Al'Aketh Turncoat" }, -- 165
        { type = "TURNIN", quest = 92643, questName = "The Turncoat", map = 2521, zone = "Zephras Isle", x = 56.0, y = 58.8 }, -- 166
        { type = "ACCEPT", quest = 92644, questName = "Unfortunate News", map = 2521, zone = "Zephras Isle", x = 56.0, y = 58.8 }, -- 167
        { type = "ACCEPT", quest = 93835, questName = "Confront Lorthuna", map = 2521, zone = "Zephras Isle", x = 65.2, y = 50.4 }, -- 168
        { type = "ACCEPT", quest = 94490, questName = "Ripped Missive", map = 2521, zone = "Zephras Isle", x = 64.8, y = 37.1 }, -- 169
        { type = "ACCEPT", quest = 94487, questName = "Unwanted and Unworthy", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 170
        { type = "ACCEPT", quest = 94485, questName = "Tears of the Lady", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 171
        { type = "ACCEPT", quest = 93165, questName = "Mercy Falls on Deaf Ears", map = 2521, zone = "Zephras Isle", x = 63.8, y = 36.0 }, -- 172
        { type = "TURNIN", quest = 94490, questName = "Ripped Missive", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 173
        { type = "COMPLETE", quest = 94487, questName = "Unwanted and Unworthy", target = "Bloody Heirloom", count = 10, map = 2521, zone = "Zephras Isle", x = 62.7, y = 36.5, note = "Bloody Heirloom" }, -- 174
        { type = "TURNIN", quest = 94487, questName = "Unwanted and Unworthy", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 175
        { type = "ACCEPT", quest = 94488, questName = "The Ties That Bind", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 176
        { type = "ACCEPT", quest = 94489, questName = "The Wounds of Betrayal", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 177
        { type = "COMPLETE", quest = 93835, questName = "Confront Lorthuna", target = "Confront Lorthuna", count = 1, map = 2521, zone = "Zephras Isle", x = 75.3, y = 53.3, note = "Confront Lorthuna" }, -- 178
        { type = "COMPLETE", quest = 94488, questName = "The Ties That Bind", target = "Commander Haalien's Severed Head", count = 1, map = 2521, zone = "Zephras Isle", x = 65.0, y = 36.7, note = "Commander Haalien's Severed Head" }, -- 179
        { type = "TURNIN", quest = 94488, questName = "The Ties That Bind", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 180
        { type = "COMPLETE", quest = 94489, questName = "The Wounds of Betrayal", target = "Find Jorel Windsinger / Injured Druids healed", count = 1, map = 2521, zone = "Zephras Isle", x = 64.5, y = 34.7, note = "Find Jorel Windsinger" }, -- 181
        { type = "COMPLETE", quest = 93165, questName = "Mercy Falls on Deaf Ears", target = "Al'Alketh Cultist's Ear", count = 10, map = 2521, zone = "Zephras Isle", x = 63.9, y = 37.2, note = "Al'Alketh Cultist's Ear" }, -- 182
        { type = "TURNIN", quest = 93165, questName = "Mercy Falls on Deaf Ears", map = 2521, zone = "Zephras Isle", x = 63.8, y = 36 }, -- 183
        { type = "TURNIN", quest = 94489, questName = "The Wounds of Betrayal", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 184
        { type = "COMPLETE", quest = 94485, questName = "Tears of the Lady", target = "Lady's Tear Moss", count = 8, map = 2521, zone = "Zephras Isle", x = 59.8, y = 40.4, note = "Lady's Tear Moss" }, -- 185
        { type = "TURNIN", quest = 94485, questName = "Tears of the Lady", map = 2521, zone = "Zephras Isle", x = 61.8, y = 39.1 }, -- 186
        { type = "ACCEPT", quest = 93159, questName = "The Strange Hermit", map = 2521, zone = "Zephras Isle", x = 54.0, y = 38.9 }, -- 187
        { type = "COMPLETE", quest = 93159, questName = "The Strange Hermit", target = "Learn more about the Strange Hermit", count = 1, map = 2521, zone = "Zephras Isle", x = 54.0, y = 38.9, note = "Learn more about the Strange Hermit" }, -- 188
        { type = "TURNIN", quest = 93159, questName = "The Strange Hermit", map = 2521, zone = "Zephras Isle", x = 54.0, y = 38.9 }, -- 189
        { type = "ACCEPT", quest = 93160, questName = "The Forest's Bounty", map = 2521, zone = "Zephras Isle", x = 54.0, y = 38.9 }, -- 190
        { type = "COMPLETE", quest = 93160, questName = "The Forest's Bounty", target = "Zephyrseed", count = 8, map = 2521, zone = "Zephras Isle", x = 56.8, y = 38.0, note = "Zephyrseed" }, -- 191
        { type = "TURNIN", quest = 93160, questName = "The Forest's Bounty", map = 2521, zone = "Zephras Isle", x = 54.0, y = 38.9 }, -- 192
        { type = "ACCEPT", quest = 94003, questName = "The Skybreaker Bulwark", npc = 252377, npcName = "Seena Skybreaker", map = 2521, zone = "Zephras Isle", x = 59.8, y = 72.8, class = { "WARRIOR" }, note = "New in Forever" }, -- 193
        { type = "COLLECT", quest = 94003, questName = "The Skybreaker Bulwark", target = "Skybreaker Bulwark", count = 1, map = 2521, zone = "Zephras Isle", x = 56.6, y = 50.4, class = { "WARRIOR" } }, -- 194
        { type = "TURNIN", quest = 94003, questName = "The Skybreaker Bulwark", npc = 252377, npcName = "Seena Skybreaker", map = 2521, zone = "Zephras Isle", x = 59.8, y = 72.8, class = { "WARRIOR" } }, -- 195
        { type = "ACCEPT", quest = 94013, questName = "Taming the Beast", npc = 252389, npcName = "Quel'ana Quickgale", map = 2521, zone = "Zephras Isle", x = 59.6, y = 72.6, class = { "HUNTER" }, note = "New in Forever" }, -- 196
        { type = "TURNIN", quest = 94013, questName = "Taming the Beast", npc = 252389, npcName = "Quel'ana Quickgale", map = 2521, zone = "Zephras Isle", x = 59.6, y = 72.6, class = { "HUNTER" } }, -- 197
        { type = "ACCEPT", quest = 94050, questName = "Training the Beast", npc = 252389, npcName = "Quel'ana Quickgale", map = 2521, zone = "Zephras Isle", x = 59.6, y = 72.6, class = { "HUNTER" }, note = "New in Forever" }, -- 198
        { type = "TURNIN", quest = 94050, questName = "Training the Beast", npc = 254411, npcName = "Quel'dora Quickgale", map = 2521, zone = "Zephras Isle", x = 59.6, y = 72.6, class = { "HUNTER" } }, -- 199
        { type = "ACCEPT", quest = 94638, questName = "Strength and Mercy", npc = 255853, npcName = "Urs'endris", map = 2521, zone = "Zephras Isle", x = 69.8, y = 61.6, class = { "DRUID" }, note = "New in Forever" }, -- 200
        { type = "KILL", quest = 94638, questName = "Strength and Mercy", npc = 258443, target = "Ur'endra", count = 1, map = 2521, zone = "Zephras Isle", x = 54, y = 65.4, class = { "DRUID" } }, -- 201
        { type = "TURNIN", quest = 94638, questName = "Strength and Mercy", npc = 255853, npcName = "Urs'endris", map = 2521, zone = "Zephras Isle", x = 69.8, y = 61.6, class = { "DRUID" } }, -- 202
        { type = "TURNIN", quest = 92644, questName = "Unfortunate News", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 203
        { type = "ACCEPT", quest = 94568, questName = "The Cult's True Plans", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 204
        { type = "TURNIN", quest = 94568, questName = "The Cult's True Plans", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 205
        { type = "TURNIN", quest = 93835, questName = "Confront Lorthuna", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 206
        { type = "ACCEPT", quest = 92640, questName = "Desperate Times", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 207
        { type = "ACCEPT", quest = 94369, questName = "The Fate of Zephras", map = 2521, zone = "Zephras Isle", x = 66.6, y = 79.9 }, -- 208
        { type = "COMPLETE", quest = 92640, questName = "Desperate Times", target = "Recruit the High Order", count = 1, map = 2521, zone = "Zephras Isle", x = 66.5, y = 79.9, note = "Recruit the High Order" }, -- 209
        { type = "COMPLETE", quest = 92640, questName = "Desperate Times", target = "Speak with Valennia Stormfist", count = 1, map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7, note = "Speak with Valennia Stormfist" }, -- 210
        { type = "COMPLETE", quest = 94369, questName = "The Fate of Zephras", target = "Speak with Talaanis Shadowsong", count = 1, map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5, note = "Speak with Talaanis Shadowsong" }, -- 211
        { type = "TURNIN", quest = 94369, questName = "The Fate of Zephras", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 212
        { type = "ACCEPT", quest = 93089, questName = "What Comes Next", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.5 }, -- 213
        { type = "TURNIN", quest = 93089, questName = "What Comes Next", map = 2521, zone = "Zephras Isle", x = 66.6, y = 80.0 }, -- 214
        { type = "COMPLETE", quest = 92640, questName = "Desperate Times", target = "Recruit the Windshapers", count = 1, map = 2521, zone = "Zephras Isle", x = 59.1, y = 79.8, note = "Recruit the Windshapers" }, -- 215
        { type = "TURNIN", quest = 92640, questName = "Desperate Times", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 216
        { type = "ACCEPT", quest = 93065, questName = "Prepare for Battle", map = 2521, zone = "Zephras Isle", x = 66.2, y = 76.7 }, -- 217
        { type = "COMPLETE", quest = 93065, questName = "Prepare for Battle", target = "Find Valennia on the Road", count = 1, map = 2521, zone = "Zephras Isle", x = 61.1, y = 70.9, note = "Find Valennia on the Road" }, -- 218
        { type = "TURNIN", quest = 93065, questName = "Prepare for Battle", map = 2521, zone = "Zephras Isle", x = 61.1, y = 70.9 }, -- 219
        { type = "ACCEPT", quest = 92947, questName = "Making Our Move", map = 2521, zone = "Zephras Isle", x = 61.1, y = 70.9 }, -- 220
        { type = "COMPLETE", quest = 92947, questName = "Making Our Move", target = "Report to Hyusaa Quickbreeze", count = 1, map = 2521, zone = "Zephras Isle", x = 63.8, y = 50.5, note = "Report to Hyusaa Quickbreeze" }, -- 221
        { type = "KILL", quest = 92947, questName = "Making Our Move", target = "Al'Aketh Guardian / Al'Aketh Guardian / Al'Aketh Guardian", count = 8, map = 2521, zone = "Zephras Isle", x = 61.3, y = 49.5, note = "Al'Aketh Guardian slain" }, -- 222
        { type = "TURNIN", quest = 92947, questName = "Making Our Move", map = 2521, zone = "Zephras Isle", x = 63.8, y = 50.5 }, -- 223
        { type = "ACCEPT", quest = 93958, questName = "The Inner Sanctum", map = 2521, zone = "Zephras Isle", x = 63.8, y = 50.5 }, -- 224
        { type = "TURNIN", quest = 93958, questName = "The Inner Sanctum", map = 2521, zone = "Zephras Isle", x = 65.2, y = 50.4 }, -- 225
    } end,
})
