-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_NIGHTELF_32_SEARING_GORGE.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_NIGHTELF_32_SEARING_GORGE",
    name = "32. Searing Gorge 46-46 (Night Elf)",
    version = 3,
    faction = "Alliance",
    race = { "NightElf" },
    minLevel = 46,
    maxLevel = 46,
    map = 1427,
    zone = "Searing Gorge",
    next = "GEN_ALLIANCE_NIGHTELF_33_THE_HINTERLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 32 of the NightElf route: level 46 to 46, 26 steps, ~120 min of play in the model (34200 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 51,
    steps = function() return {
        { type = "FLIGHTPATH", npc = 2941, npcName = "Lanie Reed", map = 1427, zone = "Searing Gorge", x = 37.9, y = 30.9 }, -- 1
        { type = "TURNIN", quest = 1560, questName = "Tooga's Quest", npc = 6015, npcName = "Torta", map = 1446, zone = "Tanaris", x = 66.6, y = 25.6 }, -- 2
        { type = "ACCEPT", quest = 3377, questName = "Prayer to Elune", npc = 8436, npcName = "Zamael Lunthistle", map = 1427, zone = "Searing Gorge", x = 29.4, y = 26.4, note = "Objectives: Zamael Story" }, -- 3
        { type = "TURNIN", quest = 3377, questName = "Prayer to Elune", npc = 8436, npcName = "Zamael Lunthistle", map = 1427, zone = "Searing Gorge", x = 29.4, y = 26.4 }, -- 4
        { type = "TURNIN", quest = 2874, questName = "Deliver to MacKinley", npc = 2501, npcName = "\"Sea Wolf\" MacKinley", map = 1434, zone = "Stranglethorn Vale", x = 27.8, y = 77 }, -- 5
        { type = "ACCEPT", quest = 2641, questName = "Sprinkle's Secret Ingredient", npc = 7583, npcName = "Sprinkle", map = 1446, zone = "Tanaris", x = 51, y = 26.8 }, -- 6
        { type = "ACCEPT", quest = 594, questName = "Message in a Bottle", map = 1434, zone = "Stranglethorn Vale", x = 36.3, y = 70.6, note = "Take Carefully Folded Note from the Half-Buried Bottle and use it to start the quest" }, -- 7
        { type = "TURNIN", quest = 594, questName = "Message in a Bottle", npc = 2634, npcName = "Princess Poobah", map = 1434, zone = "Stranglethorn Vale", x = 38.4, y = 80.6 }, -- 8
        { type = "TRAVEL", map = 1427, zone = "Searing Gorge", x = 38.1, y = 32.5, radius = 60, note = "travel to Searing Gorge (Searing Gorge)" }, -- 9
        { type = "ACCEPT", quest = 7701, questName = "WANTED: Overseer Maltorius", map = 1427, zone = "Searing Gorge", x = 37.6, y = 26.6, optional = true, note = "Elite - group up" }, -- 10
        { type = "ACCEPT", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 11
        { type = "ACCEPT", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 12
        { type = "ACCEPT", quest = 7723, questName = "Curse These Fat Fingers", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 13
        { type = "ACCEPT", quest = 7724, questName = "Fiery Menace!", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 14
        { type = "ACCEPT", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 15
        { type = "ACCEPT", quest = 7722, questName = "What the Flux?", npc = 14624, npcName = "Master Smith Burninate", map = 1427, zone = "Searing Gorge", x = 38.6, y = 28.4, optional = true, note = "Elite - group up" }, -- 16
        { type = "KILL", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 5846, target = "Dark Iron Taskmaster", count = 15, map = 1427, zone = "Searing Gorge", x = 38, y = 32, near = true }, -- 17
        { type = "KILL", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 5844, target = "Dark Iron Slaver", count = 15, map = 1427, zone = "Searing Gorge", x = 38.4, y = 38, near = true }, -- 18
        { type = "TURNIN", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 14626, npcName = "Taskmaster Scrange", map = 1427, zone = "Searing Gorge", x = 39, y = 27.5 }, -- 19
        { type = "ACCEPT", quest = 3441, questName = "Divine Retribution", npc = 8479, npcName = "Velarok Windblade", map = 1427, zone = "Searing Gorge", x = 39, y = 39, note = "Objectives: Velarok Story" }, -- 20
        { type = "TURNIN", quest = 3441, questName = "Divine Retribution", npc = 8479, npcName = "Velarok Windblade", map = 1427, zone = "Searing Gorge", x = 39, y = 39 }, -- 21
        { type = "COLLECT", quest = 7701, questName = "WANTED: Overseer Maltorius", target = "Head of Overseer Maltorius", count = 1, map = 1427, zone = "Searing Gorge", x = 41, y = 35.6, optional = true, mobs = "Overseer Maltorius" }, -- 22
        { type = "TURNIN", quest = 7701, questName = "WANTED: Overseer Maltorius", npc = 14634, npcName = "Lookout Captain Lolo Longstriker", map = 1427, zone = "Searing Gorge", x = 37.6, y = 26.6, optional = true }, -- 23
        { type = "COLLECT", quest = 7722, questName = "What the Flux?", target = "Secret Plans: Fiery Flux", count = 1, map = 1427, zone = "Searing Gorge", x = 40.6, y = 35.7, optional = true, near = true, mobs = "Overseer Maltorius" }, -- 24
        { type = "KILL", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 5840, target = "Dark Iron Steamsmith", map = 1427, zone = "Searing Gorge", x = 40, y = 48.3, near = true, note = "loot Smithing Tuyere" }, -- 25
        { type = "KILL", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 8566, target = "Dark Iron Lookout", map = 1427, zone = "Searing Gorge", x = 33.7, y = 51.9, near = true, note = "loot Lookout's Spyglass" }, -- 26
        { type = "KILL", quest = 7723, questName = "Curse These Fat Fingers", npc = 5854, target = "Heavy War Golem", count = 20, map = 1427, zone = "Searing Gorge", x = 32.5, y = 45.9, near = true }, -- 27
        { type = "KILL", quest = 7724, questName = "Fiery Menace!", npc = 5858, target = "Greater Lava Spider", count = 20, map = 1427, zone = "Searing Gorge", x = 29.5, y = 43.8, near = true }, -- 28
        { type = "ACCEPT", quest = 3442, questName = "The Flawless Flame", npc = 8479, npcName = "Velarok Windblade", map = 1427, zone = "Searing Gorge", x = 39, y = 39 }, -- 29
        { type = "COLLECT", quest = 3442, questName = "The Flawless Flame", target = "Heart of Flame", count = 4, map = 1427, zone = "Searing Gorge", x = 40.4, y = 34.2, near = true, mobs = "Blazing Elemental / Inferno Elemental / Scald" }, -- 30
        { type = "COLLECT", quest = 3442, questName = "The Flawless Flame", target = "Golem Oil", count = 4, map = 1427, zone = "Searing Gorge", x = 47, y = 36.4, near = true, mobs = "Tempered War Golem / Heavy War Golem / Magma Elemental" }, -- 31
        { type = "TURNIN", quest = 3442, questName = "The Flawless Flame", npc = 8479, npcName = "Velarok Windblade", map = 1427, zone = "Searing Gorge", x = 39, y = 39 }, -- 32
        { type = "KILL", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 9318, target = "Incendosaur", count = 20, map = 1427, zone = "Searing Gorge", x = 49.9, y = 39, near = true }, -- 33
        { type = "TURNIN", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 14626, npcName = "Taskmaster Scrange", map = 1427, zone = "Searing Gorge", x = 39, y = 27.5 }, -- 34
        { type = "TURNIN", quest = 7723, questName = "Curse These Fat Fingers", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 35
        { type = "TURNIN", quest = 7724, questName = "Fiery Menace!", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 36
        { type = "TURNIN", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 37
        { type = "ACCEPT", quest = 3443, questName = "Forging the Shaft", npc = 8479, npcName = "Velarok Windblade", map = 1427, zone = "Searing Gorge", x = 39, y = 39 }, -- 38
        { type = "TURNIN", quest = 7722, questName = "What the Flux?", npc = 14624, npcName = "Master Smith Burninate", map = 1427, zone = "Searing Gorge", x = 38.6, y = 28.4, optional = true }, -- 39
        { type = "ACCEPT", quest = 4449, questName = "Caught!", map = 1427, zone = "Searing Gorge", x = 65.6, y = 62.2 }, -- 40
        { type = "ACCEPT", quest = 3367, questName = "Suntara Stones", npc = 8284, npcName = "Dorius Stonetender", map = 1427, zone = "Searing Gorge", x = 63.9, y = 61 }, -- 41
        { type = "KILL", quest = 4449, questName = "Caught!", npc = 5839, target = "Dark Iron Geologist", count = 8, map = 1427, zone = "Searing Gorge", x = 63.9, y = 60.4, near = true }, -- 42
        { type = "COLLECT", quest = 3443, questName = "Forging the Shaft", target = "Thorium Plated Dagger", count = 8, map = 1427, zone = "Searing Gorge", x = 63.2, y = 60, near = true, mobs = "Dark Iron Geologist / Dark Iron Steamsmith / Slave Worker / Dark Iron Slaver" }, -- 43
        { type = "ACCEPT", quest = 3379, questName = "Shadoweaver", npc = 8439, npcName = "Nilith Lokrav", map = 1427, zone = "Searing Gorge", x = 41, y = 74.8, profession = "Tailoring", skill = 230 }, -- 44
        { type = "COLLECT", quest = 4449, questName = "Caught!", target = "Silk Cloth", count = 8, map = 1427, zone = "Searing Gorge", x = 40.1, y = 41.5, near = true }, -- 45
        { type = "TURNIN", quest = 3443, questName = "Forging the Shaft", npc = 8479, npcName = "Velarok Windblade", map = 1427, zone = "Searing Gorge", x = 39, y = 39 }, -- 46
        { type = "KILL", quest = 3379, questName = "Shadoweaver", npc = 8442, target = "Shadowsilk Poacher", count = 5, map = 1427, zone = "Searing Gorge", x = 58.6, y = 27.4, profession = "Tailoring", skill = 230 }, -- 47
        { type = "COMPLETE", quest = 3367, questName = "Suntara Stones", target = "Dorius Escort", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.4, note = "escort - stay close, it can fail: Dorius Escort" }, -- 48
        { type = "TURNIN", quest = 3367, questName = "Suntara Stones", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.3 }, -- 49
        { type = "ACCEPT", quest = 3368, questName = "Suntara Stones", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.3 }, -- 50
        { type = "TURNIN", quest = 4449, questName = "Caught!", map = 1427, zone = "Searing Gorge", x = 65.6, y = 62.2 }, -- 51
    } end,
})
