-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_SCOURGE_46_SILITHUS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_SCOURGE_46_SILITHUS",
    name = "46. Silithus 55-55 (Undead)",
    version = 3,
    faction = "Horde",
    race = { "Scourge" },
    minLevel = 55,
    maxLevel = 55,
    map = 1451,
    zone = "Silithus",
    next = "GEN_HORDE_SCOURGE_47_WINTERSPRING",
    author = "ForeverGuide route planner",
    notes = "Chapter 46 of the Scourge route: level 55 to 55, 24 steps, ~94 min of play in the model (40991 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 47,
    steps = function() return {
        { type = "ACCEPT", quest = 3570, questName = "Seeping Corruption", npc = 8390, npcName = "Chemist Cuely", map = 1458, zone = "Undercity", x = 48.6, y = 71.8 }, -- 1
        { type = "TURNIN", quest = 3570, questName = "Seeping Corruption", npc = 8390, npcName = "Chemist Cuely", map = 1458, zone = "Undercity", x = 48.6, y = 71.8 }, -- 2
        { type = "ACCEPT", quest = 5961, questName = "The Champion of the Banshee Queen", npc = 10181, npcName = "Lady Sylvanas Windrunner", map = 1458, zone = "Undercity", x = 57.8, y = 91.8 }, -- 3
        { type = "ACCEPT", quest = 6025, questName = "Unfinished Business", npc = 11610, npcName = "Kirsta Deepshadow", map = 1422, zone = "Western Plaguelands", x = 52, y = 28, note = "Objectives: Explore Zone, Overlook Hearthglen from a high vantage point" }, -- 4
        { type = "TURNIN", quest = 6025, questName = "Unfinished Business", npc = 11610, npcName = "Kirsta Deepshadow", map = 1422, zone = "Western Plaguelands", x = 52, y = 28 }, -- 5
        { type = "ACCEPT", quest = 7492, questName = "Camp Mojache", npc = 10879, npcName = "Harbinger Balthazad", map = 1458, zone = "Undercity", x = 68.2, y = 47.6, optional = true, note = "For Dire Maul (dungeon guide)" }, -- 6
        { type = "ACCEPT", quest = 5382, questName = "Doctor Theolen Krastinov, the Butcher", npc = 11216, npcName = "Eva Sarkhoff", map = 1422, zone = "Western Plaguelands", x = 70.2, y = 73.8, optional = true, note = "For Scholomance (dungeon guide)" }, -- 7
        { type = "ACCEPT", quest = 1471, questName = "The Binding", npc = 5675, npcName = "Carendin Halgar", map = 1458, zone = "Undercity", x = 85, y = 25.6, class = { "WARLOCK" } }, -- 8
        { type = "KILL", quest = 1471, questName = "The Binding", npc = 5676, target = "Summoned Voidwalker", count = 1, map = 1458, zone = "Undercity", x = 86.6, y = 27, near = true, class = { "WARLOCK" } }, -- 9
        { type = "TURNIN", quest = 1471, questName = "The Binding", npc = 5675, npcName = "Carendin Halgar", map = 1458, zone = "Undercity", x = 85, y = 25.6, class = { "WARLOCK" }, note = "reduced xp (10%) - you out-levelled it" }, -- 10
        { type = "TRAVEL", map = 1458, zone = "Undercity", x = 67.7, y = 37.9, radius = 60, note = "use your hearthstone (Undercity)" }, -- 11
        { type = "FLIGHTPATH", npc = 15178, npcName = "Runk Windtamer", map = 1451, zone = "Silithus", x = 48.7, y = 36.7 }, -- 12
        { type = "TURNIN", quest = 4120, questName = "The Strength of Corruption", npc = 7776, npcName = "Talo Thornhoof", map = 1444, zone = "Feralas", x = 76, y = 43.8 }, -- 13
        { type = "ACCEPT", quest = 7441, questName = "Pusillin and the Elder Azj'Tordin", npc = 14355, npcName = "Azj'Tordin", map = 1444, zone = "Feralas", x = 76.8, y = 37.4, optional = true, note = "For Dire Maul (dungeon guide)" }, -- 14
        { type = "ACCEPT", quest = 7481, questName = "Elven Legends", npc = 14373, npcName = "Sage Korolusk", map = 1444, zone = "Feralas", x = 75, y = 43.8, optional = true, note = "For Dire Maul (dungeon guide); Objectives: Master Kariel Winthalus Found" }, -- 15
        { type = "TURNIN", quest = 7481, questName = "Elven Legends", npc = 14373, npcName = "Sage Korolusk", map = 1444, zone = "Feralas", x = 75, y = 43.8, optional = true }, -- 16
        { type = "ACCEPT", quest = 7489, questName = "Lethtendris's Web", npc = 7776, npcName = "Talo Thornhoof", map = 1444, zone = "Feralas", x = 76, y = 43.8, optional = true, note = "For Dire Maul (dungeon guide)" }, -- 17
        { type = "NOTE", optional = true, text = "Ready for Dire Maul", note = "Picked up: Pusillin and the Elder Azj'Tordin, Lethtendris's Web. When you have a group, open Dire Maul under Dungeons." }, -- 18
        { type = "TURNIN", quest = 7492, questName = "Camp Mojache", npc = 7776, npcName = "Talo Thornhoof", map = 1444, zone = "Feralas", x = 76, y = 43.8, optional = true }, -- 19
        { type = "COLLECT", quest = 1803, questName = "Tome of the Cabal", target = "Moldy Tome", count = 1, map = 1424, zone = "Hillsbrad Foothills", x = 27.8, y = 72.8, class = { "WARLOCK" } }, -- 20
        { type = "COLLECT", quest = 1803, questName = "Tome of the Cabal", target = "Tattered Manuscript", count = 1, map = 1441, zone = "Thousand Needles", x = 43.4, y = 32.7, class = { "WARLOCK" } }, -- 21
        { type = "TURNIN", quest = 1803, questName = "Tome of the Cabal", npc = 6293, npcName = "Jorah Annison", map = 1458, zone = "Undercity", x = 76, y = 37.6, class = { "WARLOCK" }, note = "reduced xp (10%) - you out-levelled it" }, -- 22
        { type = "TRAVEL", map = 1451, zone = "Silithus", x = 49.9, y = 37.5, radius = 60, note = "travel to Silithus (Silithus)" }, -- 23
        { type = "HEARTH", npc = 15174, npcName = "Calandrath", map = 1451, zone = "Cenarion Hold", x = 51.9, y = 39.2, note = "talk to Calandrath and make this inn your home" }, -- 24
        { type = "ACCEPT", quest = 8307, questName = "Desert Recipe", npc = 15174, npcName = "Calandrath", map = 1451, zone = "Silithus", x = 51.8, y = 39, profession = "Cooking", skill = 285 }, -- 25
        { type = "ACCEPT", quest = 8277, questName = "Deadly Desert Venom", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 26
        { type = "ACCEPT", quest = 8280, questName = "Securing the Supply Lines", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 27
        { type = "ACCEPT", quest = 8284, questName = "The Twilight Mystery", npc = 15183, npcName = "Geologist Larksbane", map = 1451, zone = "Silithus", x = 49.7, y = 37.5 }, -- 28
        { type = "KILL", quest = 8277, questName = "Deadly Desert Venom", npc = 11735, target = "Stonelash Scorpid", count = 8, map = 1451, zone = "Silithus", x = 43, y = 41.2, near = true, note = "loot Stonelash Scorpid Stinger" }, -- 29
        { type = "KILL", quest = 8280, questName = "Securing the Supply Lines", npc = 11740, target = "Dredge Striker", count = 15, map = 1451, zone = "Silithus", x = 38.2, y = 34.3, near = true }, -- 30
        { type = "KILL", quest = 8277, questName = "Deadly Desert Venom", npc = 11738, target = "Sand Skitterer", count = 8, map = 1451, zone = "Silithus", x = 39, y = 33.2, near = true, note = "loot Sand Skitterer Fang" }, -- 31
        { type = "COLLECT", quest = 8284, questName = "The Twilight Mystery", target = "Twilight Tablet Fragment", count = 8, map = 1451, zone = "Silithus", x = 26.4, y = 15.9, near = true }, -- 32
        { type = "TURNIN", quest = 8280, questName = "Securing the Supply Lines", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 33
        { type = "ACCEPT", quest = 8281, questName = "Stepping Up Security", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 34
        { type = "TURNIN", quest = 8277, questName = "Deadly Desert Venom", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 35
        { type = "ACCEPT", quest = 8283, questName = "Wanted - Deathclasp, Terror of the Sands", map = 1451, zone = "Silithus", x = 51.3, y = 38.2, optional = true, note = "Elite - group up" }, -- 36
        { type = "TURNIN", quest = 8284, questName = "The Twilight Mystery", npc = 15183, npcName = "Geologist Larksbane", map = 1451, zone = "Silithus", x = 49.7, y = 37.5 }, -- 37
        { type = "ACCEPT", quest = 8278, questName = "Noggle's Last Hope", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 38
        { type = "KILL", quest = 8281, questName = "Stepping Up Security", npc = 11741, target = "Dredge Crusher", count = 20, map = 1451, zone = "Silithus", x = 51.9, y = 57.2, near = true }, -- 39
        { type = "KILL", quest = 8278, questName = "Noggle's Last Hope", npc = 11736, target = "Stonelash Pincer", count = 3, map = 1451, zone = "Silithus", x = 51.4, y = 62.3, near = true, note = "loot Stonelash Pincer Stinger" }, -- 40
        { type = "KILL", quest = 8278, questName = "Noggle's Last Hope", npc = 11737, target = "Stonelash Flayer", count = 3, map = 1451, zone = "Silithus", x = 49.5, y = 66.6, near = true, note = "loot Stonelash Flayer Stinger" }, -- 41
        { type = "KILL", quest = 8278, questName = "Noggle's Last Hope", npc = 11739, target = "Rock Stalker", count = 3, map = 1451, zone = "Silithus", x = 50.4, y = 69.8, near = true, note = "loot Rock Stalker Fang" }, -- 42
        { type = "TURNIN", quest = 8278, questName = "Noggle's Last Hope", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 43
        { type = "ACCEPT", quest = 8282, questName = "Noggle's Lost Satchel", npc = 15190, npcName = "Noggle Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.5 }, -- 44
        { type = "TURNIN", quest = 8281, questName = "Stepping Up Security", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 45
        { type = "COLLECT", quest = 8282, questName = "Noggle's Lost Satchel", target = "Noggle's Satchel", map = 1451, zone = "Silithus", x = 44.6, y = 91.4 }, -- 46
        { type = "TURNIN", quest = 8282, questName = "Noggle's Lost Satchel", npc = 15190, npcName = "Noggle Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.5 }, -- 47
    } end,
})
