-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_NIGHTELF_05_REDRIDGE_MOUNTAINS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_NIGHTELF_05_REDRIDGE_MOUNTAINS",
    name = "5. Redridge Mountains 18-20 (Night Elf)",
    version = 4,
    faction = "Alliance",
    race = { "NightElf" },
    minLevel = 18,
    maxLevel = 20,
    map = 1433,
    zone = "Redridge Mountains",
    next = "GEN_ALLIANCE_NIGHTELF_06_WETLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 5 of the NightElf route: level 18 to 20, 44 steps, ~112 min of play in the model (19683 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps (1 here).",
    stepCount = 91,
    steps = function() return {
        { type = "TURNIN", quest = 92744, questName = "Murloc Gills", npc = 253092, npcName = "Alba Fairmoon", map = 1436, zone = "Westfall", x = 52.4, y = 53, note = "reduced xp (80%) - you out-levelled it" }, -- 1
        { type = "TURNIN", quest = 92745, questName = "The State of the Mines", npc = 253092, npcName = "Alba Fairmoon", map = 1436, zone = "Westfall", x = 52.4, y = 53 }, -- 2
        { type = "COLLECT", quest = 256, questName = "WANTED: Chok'sul", target = "Chok'sul's Head", count = 1, map = 1432, zone = "Loch Modan", x = 79.6, y = 15, optional = true, mobs = "Chok'sul" }, -- 3
        { type = "TURNIN", quest = 256, questName = "WANTED: Chok'sul", npc = 1139, npcName = "Magistrate Bluntnose", map = 1432, zone = "Loch Modan", x = 34.6, y = 44.6, optional = true }, -- 4
        { type = "ACCEPT", quest = 3765, questName = "The Corruption Abroad", npc = 4984, npcName = "Argos Nightwhisper", map = 1453, zone = "Stormwind City", x = 21.4, y = 55.6 }, -- 5
        { type = "ACCEPT", quest = 94467, questName = "Call of Fire", npc = 257808, npcName = "Braldir Ashmantle", map = 1432, zone = "Loch Modan", x = 32, y = 66, class = { "SHAMAN" }, note = "New in Forever" }, -- 6
        { type = "COLLECT", quest = 94467, questName = "Call of Fire", target = "Glowing Ember", count = 1, map = 1411, zone = "Durotar", x = 38.7, y = 58.3, class = { "SHAMAN" }, mobs = "Minor Manifestation of Fire" }, -- 7
        { type = "TURNIN", quest = 94467, questName = "Call of Fire", map = 1411, zone = "Durotar", x = 38.9, y = 58.2, class = { "SHAMAN" } }, -- 8
        { type = "ACCEPT", quest = 6121, questName = "Lessons Anew", npc = 4217, npcName = "Mathrengyl Bearwalker", map = 1457, zone = "Darnassus", x = 35.2, y = 8, class = { "DRUID" } }, -- 9
        { type = "TURNIN", quest = 6121, questName = "Lessons Anew", npc = 11802, npcName = "Dendrite Starblaze", map = 1450, zone = "Moonglade", x = 56.2, y = 30.4, class = { "DRUID" } }, -- 10
        { type = "TRAVEL", map = 1436, zone = "Sentinel Hill", x = 52.9, y = 53.7, radius = 60, note = "use your hearthstone (Sentinel Hill)" }, -- 11
        { type = "FLIGHTPATH", npc = 931, npcName = "Ariena Stormfeather", map = 1433, zone = "Redridge Mountains", x = 25.5, y = 59.4 }, -- 12
        { type = "ACCEPT", quest = 91904, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71, note = "New in Forever" }, -- 13
        { type = "ACCEPT", quest = 91905, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71, note = "New in Forever" }, -- 14
        { type = "ACCEPT", quest = 91899, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71, note = "New in Forever" }, -- 15
        { type = "ACCEPT", quest = 91900, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71, note = "New in Forever" }, -- 16
        { type = "TURNIN", quest = 91904, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71 }, -- 17
        { type = "TURNIN", quest = 91905, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71 }, -- 18
        { type = "TURNIN", quest = 91899, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71 }, -- 19
        { type = "TURNIN", quest = 91900, questName = "A Sealed Crate", npc = 256390, npcName = "Marcy Baker", map = 1433, zone = "Redridge Mountains", x = 9.6, y = 71 }, -- 20
        { type = "ACCEPT", quest = 92747, questName = "Moonbrook Espionage", npc = 253092, npcName = "Alba Fairmoon", map = 1436, zone = "Westfall", x = 52.4, y = 53, note = "New in Forever" }, -- 21
        { type = "COLLECT", quest = 92747, questName = "Moonbrook Espionage", target = "Suspicious Industrial Supplies", count = 8, map = 1436, zone = "Westfall", x = 42.5, y = 71.7 }, -- 22
        { type = "TURNIN", quest = 92747, questName = "Moonbrook Espionage", npc = 253092, npcName = "Alba Fairmoon", map = 1436, zone = "Westfall", x = 52.4, y = 53 }, -- 23
        { type = "ACCEPT", quest = 118, questName = "The Price of Shoes", npc = 415, npcName = "Verner Osgood", map = 1433, zone = "Redridge Mountains", x = 31, y = 47.4 }, -- 24
        { type = "TURNIN", quest = 118, questName = "The Price of Shoes", npc = 514, npcName = "Smith Argus", map = 1429, zone = "Elwynn Forest", x = 41.6, y = 65.6 }, -- 25
        { type = "ACCEPT", quest = 94468, questName = "Call of Fire", map = 1432, zone = "Loch Modan", x = 31.9, y = 64.5, class = { "SHAMAN" }, note = "New in Forever" }, -- 26
        { type = "TURNIN", quest = 94468, questName = "Call of Fire", npc = 257597, npcName = "Bruegs Kindleborn", map = 1426, zone = "Dun Morogh", x = 87.6, y = 43.6, class = { "SHAMAN" } }, -- 27
        { type = "ACCEPT", quest = 6122, questName = "The Principal Source", npc = 11802, npcName = "Dendrite Starblaze", map = 1450, zone = "Moonglade", x = 56.2, y = 30.4, class = { "DRUID" } }, -- 28
        { type = "COLLECT", quest = 6122, questName = "The Principal Source", target = "Filled Cliffspring Falls Sampler", count = 1, map = 1439, zone = "Darkshore", x = 54.9, y = 33.3, class = { "DRUID" } }, -- 29
        { type = "TURNIN", quest = 6122, questName = "The Principal Source", npc = 3702, npcName = "Alanndarian Nightsong", map = 1439, zone = "Darkshore", x = 37.6, y = 40.6, class = { "DRUID" } }, -- 30
        { type = "TRAVEL", map = 1433, zone = "Redridge Mountains", x = 29.1, y = 48.2, radius = 60, note = "travel to Redridge Mountains (Redridge Mountains)" }, -- 31
        { type = "HEARTH", npc = 6727, npcName = "Innkeeper Brianna", map = 1433, zone = "Lakeshire", x = 21.9, y = 44.8, note = "talk to Innkeeper Brianna and make this inn your home" }, -- 32
        { type = "ACCEPT", quest = 129, questName = "A Free Lunch", npc = 379, npcName = "Darcy", map = 1433, zone = "Redridge Mountains", x = 26.6, y = 44.3 }, -- 33
        { type = "ACCEPT", quest = 92, questName = "Redridge Goulash", npc = 343, npcName = "Chef Breanna", map = 1433, zone = "Redridge Mountains", x = 22.7, y = 43.8 }, -- 34
        { type = "ACCEPT", quest = 127, questName = "Selling Fish", npc = 381, npcName = "Dockmaster Baren", map = 1433, zone = "Redridge Mountains", x = 27.7, y = 47.4 }, -- 35
        { type = "TURNIN", quest = 65, questName = "The Defias Brotherhood", npc = 266, npcName = "Wiley the Black", map = 1433, zone = "Redridge Mountains", x = 26.5, y = 45.4 }, -- 36
        { type = "TURNIN", quest = 2281, questName = "Redridge Rendezvous", npc = 6966, npcName = "Lucius", map = 1433, zone = "Redridge Mountains", x = 28.2, y = 52.2, class = { "ROGUE" } }, -- 37
        { type = "ACCEPT", quest = 3741, questName = "Hilary's Necklace", npc = 8965, npcName = "Shawn", map = 1433, zone = "Redridge Mountains", x = 29.3, y = 53.6 }, -- 38
        { type = "ACCEPT", quest = 125, questName = "The Lost Tools", npc = 341, npcName = "Foreman Oslow", map = 1433, zone = "Redridge Mountains", x = 32.1, y = 48.6 }, -- 39
        { type = "ACCEPT", quest = 20, questName = "Blackrock Menace", npc = 382, npcName = "Marshal Marris", map = 1433, zone = "Redridge Mountains", x = 33.5, y = 49 }, -- 40
        { type = "ACCEPT", quest = 115, questName = "Shadow Magic", npc = 382, npcName = "Marshal Marris", map = 1433, zone = "Redridge Mountains", x = 33.5, y = 49, optional = true, note = "group quest (elite mobs) - optional, take it only with company" }, -- 41
        { type = "ACCEPT", quest = 6123, questName = "Gathering the Cure", npc = 3702, npcName = "Alanndarian Nightsong", map = 1439, zone = "Darkshore", x = 37.6, y = 40.6, class = { "DRUID" } }, -- 42
        { type = "COLLECT", quest = 6123, questName = "Gathering the Cure", target = "Earthroot", count = 5, map = 1439, zone = "Darkshore", x = 47.1, y = 37, near = true, class = { "DRUID" } }, -- 43
        { type = "COLLECT", quest = 6123, questName = "Gathering the Cure", target = "Lunar Fungus", count = 12, map = 1439, zone = "Darkshore", x = 43.4, y = 46, class = { "DRUID" } }, -- 44
        { type = "TURNIN", quest = 6123, questName = "Gathering the Cure", npc = 3702, npcName = "Alanndarian Nightsong", map = 1439, zone = "Darkshore", x = 37.6, y = 40.6, class = { "DRUID" } }, -- 45
        { type = "KILL", quest = 115, questName = "Shadow Magic", npc = 436, target = "Blackrock Shadowcaster", count = 3, map = 1433, zone = "Redridge Mountains", x = 66.4, y = 53.3, optional = true, near = true }, -- 46
        { type = "ACCEPT", quest = 6124, questName = "Curing the Sick", npc = 3702, npcName = "Alanndarian Nightsong", map = 1439, zone = "Darkshore", x = 37.6, y = 40.6, class = { "DRUID" } }, -- 47
        { type = "KILL", quest = 6124, questName = "Curing the Sick", npc = 12299, target = "Sickly Deer cured", count = 10, map = 1439, zone = "Darkshore", x = 44.5, y = 24.4, class = { "DRUID" } }, -- 48
        { type = "TURNIN", quest = 6124, questName = "Curing the Sick", npc = 11802, npcName = "Dendrite Starblaze", map = 1450, zone = "Moonglade", x = 56.2, y = 30.4, class = { "DRUID" } }, -- 49
        { type = "TURNIN", quest = 115, questName = "Shadow Magic", npc = 382, npcName = "Marshal Marris", map = 1433, zone = "Redridge Mountains", x = 33.5, y = 49, optional = true }, -- 50
        { type = "COLLECT", quest = 3741, questName = "Hilary's Necklace", target = "Hilary's Necklace", map = 1433, zone = "Redridge Mountains", x = 34.1, y = 53.4, near = true }, -- 51
        { type = "TURNIN", quest = 3741, questName = "Hilary's Necklace", npc = 8962, npcName = "Hilary", map = 1433, zone = "Redridge Mountains", x = 29.2, y = 53.6 }, -- 52
        { type = "COLLECT", quest = 125, questName = "The Lost Tools", target = "Oslow's Toolbox", map = 1433, zone = "Redridge Mountains", x = 41.5, y = 54.7 }, -- 53
        { type = "COMPLETE", quest = 92, questName = "Redridge Goulash", npc = 428, target = "Dire Condor / Crisp Spider Meat", map = 1433, zone = "Redridge Mountains", x = 52.4, y = 38.8, near = true, note = "loot Tough Condor Meat" }, -- 54
        { type = "COLLECT", quest = 20, questName = "Blackrock Menace", target = "Battleworn Axe", count = 10, map = 1433, zone = "Redridge Mountains", x = 59.6, y = 42.2, near = true }, -- 55
        { type = "COLLECT", quest = 127, questName = "Selling Fish", target = "Spotted Sunfish", count = 10, map = 1433, zone = "Redridge Mountains", x = 57.1, y = 51.2, near = true }, -- 56
        { type = "ACCEPT", quest = 6125, questName = "Power over Poison", npc = 11802, npcName = "Dendrite Starblaze", map = 1450, zone = "Moonglade", x = 56.2, y = 30.4, class = { "DRUID" } }, -- 57
        { type = "TURNIN", quest = 6125, questName = "Power over Poison", npc = 4217, npcName = "Mathrengyl Bearwalker", map = 1457, zone = "Darnassus", x = 35.2, y = 8, class = { "DRUID" } }, -- 58
        { type = "COLLECT", quest = 92, questName = "Redridge Goulash", target = "Great Goretusk Snout", map = 1433, zone = "Redridge Mountains", x = 33.9, y = 71.3, near = true }, -- 59
        { type = "TURNIN", quest = 125, questName = "The Lost Tools", npc = 341, npcName = "Foreman Oslow", map = 1433, zone = "Redridge Mountains", x = 32.1, y = 48.6 }, -- 60
        { type = "ACCEPT", quest = 89, questName = "The Everstill Bridge", npc = 341, npcName = "Foreman Oslow", map = 1433, zone = "Redridge Mountains", x = 32.1, y = 48.6 }, -- 61
        { type = "TURNIN", quest = 20, questName = "Blackrock Menace", npc = 382, npcName = "Marshal Marris", map = 1433, zone = "Redridge Mountains", x = 33.5, y = 49 }, -- 62
        { type = "TURNIN", quest = 127, questName = "Selling Fish", npc = 381, npcName = "Dockmaster Baren", map = 1433, zone = "Redridge Mountains", x = 27.7, y = 47.4 }, -- 63
        { type = "TURNIN", quest = 92, questName = "Redridge Goulash", npc = 343, npcName = "Chef Breanna", map = 1433, zone = "Redridge Mountains", x = 22.7, y = 43.8 }, -- 64
        { type = "COLLECT", quest = 89, questName = "The Everstill Bridge", target = "Iron Pike / Iron Rivet", count = 5, map = 1433, zone = "Redridge Mountains", x = 20.8, y = 40, near = true }, -- 65
        { type = "TURNIN", quest = 89, questName = "The Everstill Bridge", npc = 341, npcName = "Foreman Oslow", map = 1433, zone = "Redridge Mountains", x = 32.1, y = 48.6 }, -- 66
        { type = "TURNIN", quest = 129, questName = "A Free Lunch", npc = 464, npcName = "Guard Parker", map = 1433, zone = "Redridge Mountains", x = 15.3, y = 71.5 }, -- 67
        { type = "ACCEPT", quest = 130, questName = "Visit the Herbalist", npc = 464, npcName = "Guard Parker", map = 1433, zone = "Redridge Mountains", x = 15.3, y = 71.5 }, -- 68
        { type = "ACCEPT", quest = 244, questName = "Encroaching Gnolls", npc = 464, npcName = "Guard Parker", map = 1433, zone = "Redridge Mountains", x = 15.3, y = 71.5 }, -- 69
        { type = "TURNIN", quest = 130, questName = "Visit the Herbalist", npc = 342, npcName = "Martie Jainrose", map = 1433, zone = "Redridge Mountains", x = 21.9, y = 46.3 }, -- 70
        { type = "ACCEPT", quest = 131, questName = "Delivering Daffodils", npc = 342, npcName = "Martie Jainrose", map = 1433, zone = "Redridge Mountains", x = 21.9, y = 46.3 }, -- 71
        { type = "TURNIN", quest = 131, questName = "Delivering Daffodils", npc = 379, npcName = "Darcy", map = 1433, zone = "Redridge Mountains", x = 26.6, y = 44.3 }, -- 72
        { type = "TURNIN", quest = 244, questName = "Encroaching Gnolls", npc = 1070, npcName = "Deputy Feldon", map = 1433, zone = "Redridge Mountains", x = 30.7, y = 60 }, -- 73
        { type = "ACCEPT", quest = 246, questName = "Assessing the Threat", npc = 1070, npcName = "Deputy Feldon", map = 1433, zone = "Redridge Mountains", x = 30.7, y = 60 }, -- 74
        { type = "ACCEPT", quest = 98407, questName = "Show of Force", npc = 1070, npcName = "Deputy Feldon", map = 1433, zone = "Redridge Mountains", x = 30.8, y = 60, note = "New in Forever" }, -- 75
        { type = "COLLECT", quest = 98407, questName = "Show of Force", target = "Spiked Collar", count = 5, map = 1433, zone = "Redridge Mountains", x = 30, y = 81.2, mobs = "Redridge Thrasher" }, -- 76
        { type = "KILL", quest = 246, questName = "Assessing the Threat", npc = 424, target = "Redridge Poacher / Redridge Mongrel", count = 10, map = 1433, zone = "Redridge Mountains", x = 31, y = 79.5, near = true }, -- 77
        { type = "TURNIN", quest = 246, questName = "Assessing the Threat", npc = 1070, npcName = "Deputy Feldon", map = 1433, zone = "Redridge Mountains", x = 30.7, y = 60 }, -- 78
        { type = "TURNIN", quest = 98407, questName = "Show of Force", npc = 1070, npcName = "Deputy Feldon", map = 1433, zone = "Redridge Mountains", x = 30.8, y = 60 }, -- 79
        { type = "GRIND", npc = 485, target = "Blackrock Outrunner", level = 20, map = 1433, zone = "Redridge Mountains", x = 40.6, y = 41.5, near = true, note = "grind Blackrock Outrunner (level 20-21) to level 20 - nothing worth questing at 19" }, -- 80
        { type = "ACCEPT", quest = 169, questName = "WANTED: Gath'Ilzogg", map = 1433, zone = "Redridge Mountains", x = 29.6, y = 46.3, optional = true, note = "Elite - group up" }, -- 81
        { type = "ACCEPT", quest = 150, questName = "Murloc Poachers", npc = 381, npcName = "Dockmaster Baren", map = 1433, zone = "Redridge Mountains", x = 27.7, y = 47.4 }, -- 82
        { type = "ACCEPT", quest = 91, questName = "Solomon's Law", npc = 900, npcName = "Bailiff Conacher", map = 1433, zone = "Redridge Mountains", x = 29.7, y = 44.3 }, -- 83
        { type = "COLLECT", quest = 150, questName = "Murloc Poachers", target = "Murloc Fin", count = 8, map = 1433, zone = "Redridge Mountains", x = 39.2, y = 49.1, near = true }, -- 84
        { type = "COLLECT", quest = 91, questName = "Solomon's Law", target = "Shadowhide Pendant", count = 10, map = 1433, zone = "Redridge Mountains", x = 71.4, y = 54.2, near = true }, -- 85
        { type = "ACCEPT", quest = 19, questName = "Tharil'zun", npc = 382, npcName = "Marshal Marris", map = 1433, zone = "Redridge Mountains", x = 33.4, y = 48.8, optional = true, note = "Elite - group up" }, -- 86
        { type = "COLLECT", quest = 19, questName = "Tharil'zun", target = "Tharil'zun's Head", count = 1, map = 1433, zone = "Redridge Mountains", x = 69.2, y = 59.4, optional = true, mobs = "Tharil'zun" }, -- 87
        { type = "TURNIN", quest = 19, questName = "Tharil'zun", npc = 382, npcName = "Marshal Marris", map = 1433, zone = "Redridge Mountains", x = 33.4, y = 48.8, optional = true }, -- 88
        { type = "ACCEPT", quest = 1097, questName = "Elmore's Task", npc = 415, npcName = "Verner Osgood", map = 1433, zone = "Redridge Mountains", x = 31, y = 47.4 }, -- 89
        { type = "TURNIN", quest = 150, questName = "Murloc Poachers", npc = 381, npcName = "Dockmaster Baren", map = 1433, zone = "Redridge Mountains", x = 27.7, y = 47.4 }, -- 90
        { type = "TURNIN", quest = 91, questName = "Solomon's Law", npc = 900, npcName = "Bailiff Conacher", map = 1433, zone = "Redridge Mountains", x = 29.7, y = 44.3 }, -- 91
    } end,
})
