-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_SCOURGE_43_UNDERCITY.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_SCOURGE_43_UNDERCITY",
    name = "43. Undercity 53-53 (Undead)",
    version = 3,
    faction = "Horde",
    race = { "Scourge" },
    minLevel = 53,
    maxLevel = 53,
    map = 1458,
    zone = "Undercity",
    next = "GEN_HORDE_SCOURGE_44_WESTERN_PLAGUELANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 43 of the Scourge route: level 53 to 53, 5 steps, ~2 min of play in the model (148023 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps.",
    stepCount = 26,
    steps = function() return {
        { type = "ACCEPT", quest = 3564, questName = "Andron's Payment to Jediga", npc = 6522, npcName = "Andron Gant", map = 1458, zone = "Undercity", x = 54.6, y = 75.6 }, -- 1
        { type = "TURNIN", quest = 3564, questName = "Andron's Payment to Jediga", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.4, y = 51.4 }, -- 2
        { type = "ACCEPT", quest = 7818, questName = "A Donation of Runecloth", npc = 14729, npcName = "Ralston Farnsley", map = 1458, zone = "Undercity", x = 71.6, y = 28.8 }, -- 3
        { type = "TURNIN", quest = 7818, questName = "A Donation of Runecloth", npc = 14729, npcName = "Ralston Farnsley", map = 1458, zone = "Undercity", x = 71.6, y = 28.8 }, -- 4
        { type = "ACCEPT", quest = 8153, questName = "Courser Antlers", npc = 8405, npcName = "Ogtinc", map = 1447, zone = "Azshara", x = 42.4, y = 42.6, class = { "HUNTER" } }, -- 5
        { type = "ACCEPT", quest = 8255, questName = "Of Coursers We Know", npc = 8405, npcName = "Ogtinc", map = 1447, zone = "Azshara", x = 42.4, y = 42.6, class = { "PRIEST" } }, -- 6
        { type = "COLLECT", quest = 8153, questName = "Courser Antlers", target = "Perfect Courser Antler", count = 2, map = 1447, zone = "Azshara", x = 37.8, y = 69.2, class = { "HUNTER" }, mobs = "Mosshoof Courser" }, -- 7
        { type = "TURNIN", quest = 8153, questName = "Courser Antlers", npc = 8405, npcName = "Ogtinc", map = 1447, zone = "Azshara", x = 42.4, y = 42.6, class = { "HUNTER" } }, -- 8
        { type = "COLLECT", quest = 8255, questName = "Of Coursers We Know", target = "Healthy Courser Gland", count = 4, map = 1447, zone = "Azshara", x = 37.8, y = 69.2, class = { "PRIEST" }, mobs = "Mosshoof Courser" }, -- 9
        { type = "TURNIN", quest = 8255, questName = "Of Coursers We Know", npc = 8405, npcName = "Ogtinc", map = 1447, zone = "Azshara", x = 42.4, y = 42.6, class = { "PRIEST" } }, -- 10
        { type = "ACCEPT", quest = 8252, questName = "The Siren's Coral", npc = 8379, npcName = "Archmage Xylem", map = 1447, zone = "Azshara", x = 29.2, y = 40.2, class = { "MAGE" } }, -- 11
        { type = "COLLECT", quest = 8252, questName = "The Siren's Coral", target = "Enchanted Coral", count = 6, map = 1447, zone = "Azshara", x = 40.2, y = 53, class = { "MAGE" }, mobs = "Spitelash Siren" }, -- 12
        { type = "TURNIN", quest = 8252, questName = "The Siren's Coral", npc = 8379, npcName = "Archmage Xylem", map = 1447, zone = "Azshara", x = 29.2, y = 40.2, class = { "MAGE" } }, -- 13
        { type = "ACCEPT", quest = 1803, questName = "Tome of the Cabal", npc = 6293, npcName = "Jorah Annison", map = 1458, zone = "Undercity", x = 76, y = 37.6, class = { "WARLOCK" } }, -- 14
        { type = "ACCEPT", quest = 1473, questName = "Creature of the Void", npc = 5675, npcName = "Carendin Halgar", map = 1458, zone = "Undercity", x = 85, y = 25.6, class = { "WARLOCK" } }, -- 15
        { type = "COLLECT", quest = 1473, questName = "Creature of the Void", target = "Egalin's Grimoire", count = 1, map = 1420, zone = "Tirisfal Glades", x = 51.1, y = 67.6, class = { "WARLOCK" } }, -- 16
        { type = "TURNIN", quest = 1473, questName = "Creature of the Void", npc = 5675, npcName = "Carendin Halgar", map = 1458, zone = "Undercity", x = 85, y = 25.6, class = { "WARLOCK" }, note = "reduced xp (10%) - you out-levelled it" }, -- 17
        { type = "TRAVEL", map = 1458, zone = "Undercity", x = 67.7, y = 37.9, radius = 60, note = "use your hearthstone (Undercity)" }, -- 18
        { type = "TRAVEL", map = 1458, zone = "Undercity", x = 59.2, y = 54.8, radius = 60, note = "travel to Undercity (Undercity)" }, -- 19
        { type = "TURNIN", quest = 3568, questName = "Seeping Corruption", npc = 8390, npcName = "Chemist Cuely", map = 1458, zone = "Undercity", x = 48.6, y = 71.8 }, -- 20
        { type = "ACCEPT", quest = 4294, questName = "... and a Batch of Ooze", npc = 10136, npcName = "Chemist Fuely", map = 1458, zone = "Undercity", x = 47.5, y = 73.4 }, -- 21
        { type = "COLLECT", quest = 4294, questName = "... and a Batch of Ooze", target = "Pure Un'Goro Sample", count = 5, map = 1458, zone = "Undercity", x = 47.7, y = 73.6 }, -- 22
        { type = "TURNIN", quest = 4294, questName = "... and a Batch of Ooze", npc = 10136, npcName = "Chemist Fuely", map = 1458, zone = "Undercity", x = 47.5, y = 73.4 }, -- 23
        { type = "ACCEPT", quest = 3569, questName = "Seeping Corruption", npc = 8390, npcName = "Chemist Cuely", map = 1458, zone = "Undercity", x = 48.6, y = 71.8 }, -- 24
        { type = "TURNIN", quest = 3569, questName = "Seeping Corruption", npc = 8393, npcName = "Thersa Windsong", map = 1458, zone = "Undercity", x = 49, y = 71.2 }, -- 25
        { type = "TURNIN", quest = 5050, questName = "Good Luck Charm", npc = 10778, npcName = "Janice Felstone", map = 1422, zone = "Western Plaguelands", x = 38.4, y = 54 }, -- 26
    } end,
})
